# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/oras-project/oras
%global goipath         oras.land/oras
%global forgeurl        https://github.com/oras-project/oras
Version:                1.3.2

%gometa -L
%forgemeta


Name:           oras
Release:        0.2%{?dist}
Summary:        OCI registry client - managing content like artifacts, images, packages

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
OCI registry client - managing content like artifacts, images, packages.

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc docs CODE_OF_CONDUCT.md CONTRIBUTING.md MAINTAINERS.md OWNERS.md README.md
%doc SECURITY.md
%{_bindir}/oras


%changelog
%autochangelog
