# https://github.com/kubernetes/kube-state-metrics
%bcond check 1

%global goipath         k8s.io/kube-state-metrics/v2
%global forgeurl        https://github.com/kubernetes/kube-state-metrics
Version:                2.20.0

%gometa -L -f

Name:           kube-state-metrics
Release:        0.2%{?dist}
Summary:        Add-on agent to generate and expose cluster-level metrics

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

Patch0:         0001-bump-vendored-go-git-to-v5.19.2-for-CVE-2026-71556.patch

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.22

%description
kube-state-metrics is a simple service that listens to the Kubernetes API
server and generates metrics about the state of Kubernetes objects.

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export GOFLAGS="-mod=vendor -buildvcs=false"
export GO_LDFLAGS="-X github.com/prometheus/common/version.Version=v%{version}"
%gobuild -o %{gobuilddir}/bin/kube-state-metrics %{goipath}

%{gobuilddir}/bin/kube-state-metrics completion bash > kube-state-metrics.bash
%{gobuilddir}/bin/kube-state-metrics completion fish > kube-state-metrics.fish
%{gobuilddir}/bin/kube-state-metrics completion zsh > kube-state-metrics.zsh

%install
%go_vendor_license_install -c %{S:2}
install -D -p -m 0755 %{gobuilddir}/bin/kube-state-metrics %{buildroot}%{_bindir}/kube-state-metrics
install -D -p -m 0644 kube-state-metrics.bash %{buildroot}%{bash_completions_dir}/kube-state-metrics
install -D -p -m 0644 kube-state-metrics.fish %{buildroot}%{fish_completions_dir}/kube-state-metrics.fish
install -D -p -m 0644 kube-state-metrics.zsh %{buildroot}%{zsh_completions_dir}/_kube-state-metrics

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
# E2E tests require a live Kubernetes cluster.
%gotest $(go list ./... | grep -Ev '/tests/e2e($|/)')
%endif

%files -f %{go_vendor_license_filelist}
%doc CHANGELOG.md README.md
%{_bindir}/kube-state-metrics
%{bash_completions_dir}/kube-state-metrics
%{fish_completions_dir}/kube-state-metrics.fish
%{zsh_completions_dir}/_kube-state-metrics

%changelog
%autochangelog
