%bcond check 1

# https://github.com/prometheus/prometheus
%global goipath         github.com/prometheus/prometheus
%global forgeurl        https://github.com/prometheus/prometheus
Version:                3.13.1

%gometa -L -f

Name:           prometheus3.13
Release:        0.3%{?dist}
Summary:        Monitoring system and time series database
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
# Upstream-built UI assets. Avoids architecture-specific Node.js native modules at RPM build time.
Source2:        https://github.com/prometheus/prometheus/releases/download/v%{version}/prometheus-web-ui-%{version}.tar.gz
Source3:        go-vendor-tools.toml
Patch0:         0001-Disable-pprof-debug-endpoints.patch
Patch1:         0002-cve-2026-56852-update-golang.org-x-text-to-v0.39.0.patch

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.25

# Generated with: bash npm-prometheus.sh web/ui/mantine-ui/package.json
# The local @prometheus-io/codemirror-promql workspace needs its version supplied manually.
Provides: bundled(nodejs-clsx) = 2.1.1
Provides: bundled(nodejs-codemirror-autocomplete) = 6.20.3
Provides: bundled(nodejs-codemirror-commands) = 6.10.3
Provides: bundled(nodejs-codemirror-language) = 6.12.3
Provides: bundled(nodejs-codemirror-lint) = 6.9.7
Provides: bundled(nodejs-codemirror-search) = 6.7.0
Provides: bundled(nodejs-codemirror-state) = 6.6.0
Provides: bundled(nodejs-codemirror-view) = 6.43.1
Provides: bundled(nodejs-dayjs) = 1.11.21
Provides: bundled(nodejs-floating-ui-dom) = 1.7.6
Provides: bundled(nodejs-highlight.js) = 11.11.1
Provides: bundled(nodejs-lezer-common) = 1.5.2
Provides: bundled(nodejs-lezer-highlight) = 1.2.3
Provides: bundled(nodejs-lodash) = 4.18.1
Provides: bundled(nodejs-mantine-code-highlight) = 9.3.1
Provides: bundled(nodejs-mantine-core) = 9.3.1
Provides: bundled(nodejs-mantine-dates) = 9.3.1
Provides: bundled(nodejs-mantine-hooks) = 9.3.1
Provides: bundled(nodejs-mantine-notifications) = 9.3.1
Provides: bundled(nodejs-microsoft-fetch-event-source) = 2.0.1
Provides: bundled(nodejs-nexucis-fuzzy) = 0.5.1
Provides: bundled(nodejs-nexucis-kvsearch) = 0.9.1
Provides: bundled(nodejs-prometheus-io-codemirror-promql) = 0.313.0
Provides: bundled(nodejs-react) = 19.2.7
Provides: bundled(nodejs-react-dom) = 19.2.7
Provides: bundled(nodejs-react-infinite-scroll-component) = 6.1.1
Provides: bundled(nodejs-react-redux) = 9.3.0
Provides: bundled(nodejs-react-router-dom) = 7.17.0
Provides: bundled(nodejs-reduxjs-toolkit) = 2.12.0
Provides: bundled(nodejs-sanitize-html) = 2.17.5
Provides: bundled(nodejs-tabler-icons-react) = 3.44.0
Provides: bundled(nodejs-tanstack-react-query) = 5.101.0
Provides: bundled(nodejs-testing-library-jest-dom) = 6.9.1
Provides: bundled(nodejs-testing-library-react) = 16.3.2
Provides: bundled(nodejs-types-lodash) = 4.17.24
Provides: bundled(nodejs-types-sanitize-html) = 2.16.1
Provides: bundled(nodejs-uiw-react-codemirror) = 4.25.10
Provides: bundled(nodejs-uplot) = 1.6.32
Provides: bundled(nodejs-uplot-react) = 1.2.4
Provides: bundled(nodejs-use-query-params) = 2.2.2
Provides: npm(prometheus-io-mantine-ui) = 0.313.0

%description
Prometheus is a monitoring system and time series database.

%prep
%goprep -p1
tar -xf %{S:1}
tar -xzf %{S:2}
cp -r static/ web/ui/
rm -rf static/

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:3}

%build
%global gomodulesmode GO111MODULE=on
scripts/compress_assets.sh
export GOWORK=off
export GO_BUILDTAGS="builtinassets"
export GOFLAGS="-mod=vendor -buildvcs=false"
export GO_LDFLAGS="-X github.com/prometheus/common/version.Version=%{version}"
%gobuild -o %{gobuilddir}/bin/prometheus %{goipath}/cmd/prometheus
%gobuild -o %{gobuilddir}/bin/promtool %{goipath}/cmd/promtool

%install
%go_vendor_license_install -c %{S:3}
install -D -p -m 0755 %{gobuilddir}/bin/prometheus %{buildroot}%{_bindir}/prometheus
install -D -p -m 0755 %{gobuilddir}/bin/promtool %{buildroot}%{_bindir}/promtool

%check
%go_vendor_license_check -c %{S:3}
%if %{with check}
export GOWORK=off
# pprof debug routes are deliberately removed by Patch0.
skip_tests=(
    TestDebugHandler # asserts the upstream /debug/pprof endpoint returns HTTP 200
)
skip_pattern=$(IFS='|'; echo "${skip_tests[*]}")
%gotest -skip "${skip_pattern}" ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc README.md NOTICE
%{_bindir}/prometheus
%{_bindir}/promtool

%changelog
%autochangelog
