%bcond check 1

# https://github.com/prometheus/prometheus
%global goipath         github.com/prometheus/prometheus
%global forgeurl        https://github.com/prometheus/prometheus
Version:                3.13.2

%gometa -L -f

Name:           prometheus3.13
Release:        0.1%{?dist}
Summary:        Monitoring system and time series database
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
# pnpm CLI and architecture-neutral content-addressed store, populated by the update hook.
Source2:        prometheus-pnpm-cache-%{version}.tar.bz2
Source3:        go-vendor-tools.toml
Patch0:         0001-Disable-pprof-debug-endpoints.patch
Patch1:         0002-cve-2026-56852-update-golang.org-x-text-to-v0.39.0.patch
Patch2:         0003-pnpm-cache-both-rpm-architectures.patch
Patch3:         0004-cve-2026-53669-bump-react-router-to-7.18.0.patch

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.25
BuildRequires:  nodejs24
BuildRequires:  nodejs24-bin

# BEGIN generated bundled npm Provides
Provides:       bundled(npm(@adobe/css-tools)) = 4.5.0
Provides:       bundled(npm(@babel/code-frame)) = 7.29.7
Provides:       bundled(npm(@babel/helper-validator-identifier)) = 7.29.7
Provides:       bundled(npm(@babel/runtime)) = 7.29.7
Provides:       bundled(npm(@codemirror/autocomplete)) = 6.20.3
Provides:       bundled(npm(@codemirror/commands)) = 6.10.3
Provides:       bundled(npm(@codemirror/language)) = 6.12.3
Provides:       bundled(npm(@codemirror/lint)) = 6.9.7
Provides:       bundled(npm(@codemirror/search)) = 6.7.0
Provides:       bundled(npm(@codemirror/state)) = 6.6.0
Provides:       bundled(npm(@codemirror/theme-one-dark)) = 6.1.3
Provides:       bundled(npm(@codemirror/view)) = 6.43.1
Provides:       bundled(npm(@floating-ui/core)) = 1.7.5
Provides:       bundled(npm(@floating-ui/dom)) = 1.7.6
Provides:       bundled(npm(@floating-ui/react)) = 0.27.19
Provides:       bundled(npm(@floating-ui/react-dom)) = 2.1.8
Provides:       bundled(npm(@floating-ui/utils)) = 0.2.11
Provides:       bundled(npm(@forevolve/bootstrap-dark)) = 4.0.2
Provides:       bundled(npm(@fortawesome/fontawesome-common-types)) = 6.7.2
Provides:       bundled(npm(@fortawesome/fontawesome-svg-core)) = 6.7.2
Provides:       bundled(npm(@fortawesome/free-solid-svg-icons)) = 6.7.2
Provides:       bundled(npm(@fortawesome/react-fontawesome)) = 0.2.6
Provides:       bundled(npm(@hypnosphi/create-react-context)) = 0.3.1
Provides:       bundled(npm(@lezer/common)) = 1.5.2
Provides:       bundled(npm(@lezer/highlight)) = 1.2.3
Provides:       bundled(npm(@lezer/lr)) = 1.4.10
Provides:       bundled(npm(@mantine/code-highlight)) = 9.3.1
Provides:       bundled(npm(@mantine/core)) = 9.3.1
Provides:       bundled(npm(@mantine/dates)) = 9.3.1
Provides:       bundled(npm(@mantine/hooks)) = 9.3.1
Provides:       bundled(npm(@mantine/notifications)) = 9.3.1
Provides:       bundled(npm(@mantine/store)) = 9.3.1
Provides:       bundled(npm(@marijn/find-cluster-break)) = 1.0.2
Provides:       bundled(npm(@microsoft/fetch-event-source)) = 2.0.1
Provides:       bundled(npm(@nexucis/fuzzy)) = 0.5.1
Provides:       bundled(npm(@nexucis/kvsearch)) = 0.9.1
Provides:       bundled(npm(@parcel/watcher)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-android-arm64)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-darwin-arm64)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-darwin-x64)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-freebsd-x64)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-linux-arm-glibc)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-linux-arm-musl)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-linux-arm64-glibc)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-linux-arm64-musl)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-linux-x64-glibc)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-linux-x64-musl)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-win32-arm64)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-win32-ia32)) = 2.5.6
Provides:       bundled(npm(@parcel/watcher-win32-x64)) = 2.5.6
Provides:       bundled(npm(@reduxjs/toolkit)) = 2.12.0
Provides:       bundled(npm(@standard-schema/spec)) = 1.1.0
Provides:       bundled(npm(@standard-schema/utils)) = 0.3.0
Provides:       bundled(npm(@tabler/icons)) = 3.44.0
Provides:       bundled(npm(@tabler/icons-react)) = 3.44.0
Provides:       bundled(npm(@tanstack/query-core)) = 5.101.0
Provides:       bundled(npm(@tanstack/react-query)) = 5.101.0
Provides:       bundled(npm(@testing-library/dom)) = 10.4.1
Provides:       bundled(npm(@testing-library/jest-dom)) = 6.9.1
Provides:       bundled(npm(@testing-library/react)) = 16.3.2
Provides:       bundled(npm(@types/aria-query)) = 5.0.4
Provides:       bundled(npm(@types/http-proxy)) = 1.17.17
Provides:       bundled(npm(@types/lodash)) = 4.17.24
Provides:       bundled(npm(@types/node)) = 22.19.21
Provides:       bundled(npm(@types/react)) = 19.2.17
Provides:       bundled(npm(@types/react-dom)) = 19.2.3
Provides:       bundled(npm(@types/sanitize-html)) = 2.16.1
Provides:       bundled(npm(@types/use-sync-external-store)) = 0.0.6
Provides:       bundled(npm(@uiw/codemirror-extensions-basic-setup)) = 4.25.10
Provides:       bundled(npm(@uiw/react-codemirror)) = 4.25.10
Provides:       bundled(npm(ansi-regex)) = 5.0.1
Provides:       bundled(npm(ansi-styles)) = 5.2.0
Provides:       bundled(npm(aria-query)) = 5.3.0
Provides:       bundled(npm(aria-query)) = 5.3.2
Provides:       bundled(npm(bootstrap)) = 4.6.2
Provides:       bundled(npm(braces)) = 3.0.3
Provides:       bundled(npm(call-bind)) = 1.0.9
Provides:       bundled(npm(call-bind-apply-helpers)) = 1.0.2
Provides:       bundled(npm(call-bound)) = 1.0.4
Provides:       bundled(npm(chokidar)) = 5.0.0
Provides:       bundled(npm(classnames)) = 2.5.1
Provides:       bundled(npm(clsx)) = 2.1.1
Provides:       bundled(npm(codemirror)) = 6.0.2
Provides:       bundled(npm(compute-scroll-into-view)) = 3.1.1
Provides:       bundled(npm(cookie)) = 1.1.1
Provides:       bundled(npm(copy-to-clipboard)) = 3.3.3
Provides:       bundled(npm(crelt)) = 1.0.6
Provides:       bundled(npm(css.escape)) = 1.5.1
Provides:       bundled(npm(csstype)) = 3.2.3
Provides:       bundled(npm(dayjs)) = 1.11.20
Provides:       bundled(npm(dayjs)) = 1.11.21
Provides:       bundled(npm(debug)) = 4.4.3
Provides:       bundled(npm(deep-equal)) = 1.1.2
Provides:       bundled(npm(deepmerge)) = 4.3.1
Provides:       bundled(npm(define-data-property)) = 1.1.4
Provides:       bundled(npm(define-properties)) = 1.2.1
Provides:       bundled(npm(dequal)) = 2.0.3
Provides:       bundled(npm(detect-libc)) = 2.1.2
Provides:       bundled(npm(detect-node-es)) = 1.1.0
Provides:       bundled(npm(dom-accessibility-api)) = 0.5.16
Provides:       bundled(npm(dom-accessibility-api)) = 0.6.3
Provides:       bundled(npm(dom-helpers)) = 3.4.0
Provides:       bundled(npm(dom-helpers)) = 5.2.1
Provides:       bundled(npm(dom-serializer)) = 2.0.0
Provides:       bundled(npm(domelementtype)) = 2.3.0
Provides:       bundled(npm(domhandler)) = 5.0.3
Provides:       bundled(npm(domutils)) = 3.2.2
Provides:       bundled(npm(downshift)) = 9.3.6
Provides:       bundled(npm(dunder-proto)) = 1.0.1
Provides:       bundled(npm(entities)) = 4.5.0
Provides:       bundled(npm(entities)) = 7.0.1
Provides:       bundled(npm(es-define-property)) = 1.0.1
Provides:       bundled(npm(es-errors)) = 1.3.0
Provides:       bundled(npm(es-object-atoms)) = 1.1.2
Provides:       bundled(npm(escape-string-regexp)) = 4.0.0
Provides:       bundled(npm(eventemitter3)) = 4.0.7
Provides:       bundled(npm(fill-range)) = 7.1.1
Provides:       bundled(npm(follow-redirects)) = 1.16.0
Provides:       bundled(npm(fsevents)) = 2.3.3
Provides:       bundled(npm(function-bind)) = 1.1.2
Provides:       bundled(npm(functions-have-names)) = 1.2.3
Provides:       bundled(npm(get-intrinsic)) = 1.3.0
Provides:       bundled(npm(get-nonce)) = 1.0.1
Provides:       bundled(npm(get-proto)) = 1.0.1
Provides:       bundled(npm(gopd)) = 1.2.0
Provides:       bundled(npm(gud)) = 1.0.0
Provides:       bundled(npm(has-property-descriptors)) = 1.0.2
Provides:       bundled(npm(has-symbols)) = 1.1.0
Provides:       bundled(npm(has-tostringtag)) = 1.0.2
Provides:       bundled(npm(hasown)) = 2.0.3
Provides:       bundled(npm(highlight.js)) = 11.11.1
Provides:       bundled(npm(history)) = 4.10.1
Provides:       bundled(npm(hoist-non-react-statics)) = 3.3.2
Provides:       bundled(npm(htmlparser2)) = 10.1.0
Provides:       bundled(npm(http-proxy)) = 1.18.1
Provides:       bundled(npm(http-proxy-middleware)) = 3.0.6
Provides:       bundled(npm(immer)) = 11.1.8
Provides:       bundled(npm(immutable)) = 5.1.5
Provides:       bundled(npm(indent-string)) = 4.0.0
Provides:       bundled(npm(is-arguments)) = 1.2.0
Provides:       bundled(npm(is-date-object)) = 1.1.0
Provides:       bundled(npm(is-extglob)) = 2.1.1
Provides:       bundled(npm(is-glob)) = 4.0.3
Provides:       bundled(npm(is-number)) = 7.0.0
Provides:       bundled(npm(is-plain-object)) = 5.0.0
Provides:       bundled(npm(is-regex)) = 1.2.1
Provides:       bundled(npm(isarray)) = 0.0.1
Provides:       bundled(npm(jquery)) = 3.7.1
Provides:       bundled(npm(jquery.flot.tooltip)) = 0.9.0
Provides:       bundled(npm(js-tokens)) = 4.0.0
Provides:       bundled(npm(launder)) = 1.7.1
Provides:       bundled(npm(lodash)) = 4.18.1
Provides:       bundled(npm(loose-envify)) = 1.4.0
Provides:       bundled(npm(lru-cache)) = 11.5.1
Provides:       bundled(npm(lz-string)) = 1.5.0
Provides:       bundled(npm(math-intrinsics)) = 1.1.0
Provides:       bundled(npm(micromatch)) = 4.0.8
Provides:       bundled(npm(min-indent)) = 1.0.1
Provides:       bundled(npm(moment)) = 2.30.1
Provides:       bundled(npm(moment-timezone)) = 0.6.2
Provides:       bundled(npm(ms)) = 2.1.3
Provides:       bundled(npm(nanoid)) = 3.3.12
Provides:       bundled(npm(node-addon-api)) = 7.1.1
Provides:       bundled(npm(object-assign)) = 4.1.1
Provides:       bundled(npm(object-is)) = 1.1.6
Provides:       bundled(npm(object-keys)) = 1.1.1
Provides:       bundled(npm(parse-srcset)) = 1.0.2
Provides:       bundled(npm(path-to-regexp)) = 1.9.0
Provides:       bundled(npm(picocolors)) = 1.1.1
Provides:       bundled(npm(picomatch)) = 2.3.2
Provides:       bundled(npm(picomatch)) = 4.0.4
Provides:       bundled(npm(popper.js)) = 1.16.1
Provides:       bundled(npm(postcss)) = 8.5.15
Provides:       bundled(npm(pretty-format)) = 27.5.1
Provides:       bundled(npm(prop-types)) = 15.8.1
Provides:       bundled(npm(react)) = 17.0.2
Provides:       bundled(npm(react)) = 19.2.7
Provides:       bundled(npm(react-copy-to-clipboard)) = 5.1.1
Provides:       bundled(npm(react-dom)) = 17.0.2
Provides:       bundled(npm(react-dom)) = 19.2.7
Provides:       bundled(npm(react-infinite-scroll-component)) = 6.1.1
Provides:       bundled(npm(react-is)) = 16.13.1
Provides:       bundled(npm(react-is)) = 17.0.2
Provides:       bundled(npm(react-is)) = 18.3.1
Provides:       bundled(npm(react-lifecycles-compat)) = 3.0.4
Provides:       bundled(npm(react-number-format)) = 5.4.5
Provides:       bundled(npm(react-popper)) = 1.3.11
Provides:       bundled(npm(react-redux)) = 9.3.0
Provides:       bundled(npm(react-remove-scroll)) = 2.7.2
Provides:       bundled(npm(react-remove-scroll-bar)) = 2.3.8
Provides:       bundled(npm(react-resize-detector)) = 7.1.2
Provides:       bundled(npm(react-router)) = 5.3.4
Provides:       bundled(npm(react-router)) = 7.17.0
Provides:       bundled(npm(react-router-dom)) = 5.3.4
Provides:       bundled(npm(react-router-dom)) = 7.17.0
Provides:       bundled(npm(react-shallow-renderer)) = 16.15.0
Provides:       bundled(npm(react-style-singleton)) = 2.2.3
Provides:       bundled(npm(react-test-renderer)) = 17.0.2
Provides:       bundled(npm(react-transition-group)) = 3.0.0
Provides:       bundled(npm(react-transition-group)) = 4.4.5
Provides:       bundled(npm(reactstrap)) = 8.10.1
Provides:       bundled(npm(readdirp)) = 5.0.0
Provides:       bundled(npm(redent)) = 3.0.0
Provides:       bundled(npm(redux)) = 5.0.1
Provides:       bundled(npm(redux-thunk)) = 3.1.0
Provides:       bundled(npm(regexp.prototype.flags)) = 1.5.4
Provides:       bundled(npm(requires-port)) = 1.0.0
Provides:       bundled(npm(reselect)) = 5.2.0
Provides:       bundled(npm(resolve-pathname)) = 3.0.0
Provides:       bundled(npm(sanitize-html)) = 2.17.5
Provides:       bundled(npm(sass)) = 1.101.0
Provides:       bundled(npm(scheduler)) = 0.20.2
Provides:       bundled(npm(scheduler)) = 0.27.0
Provides:       bundled(npm(serialize-query-params)) = 2.0.4
Provides:       bundled(npm(set-cookie-parser)) = 2.7.2
Provides:       bundled(npm(set-function-length)) = 1.2.2
Provides:       bundled(npm(set-function-name)) = 2.0.2
Provides:       bundled(npm(source-map-js)) = 1.2.1
Provides:       bundled(npm(strip-indent)) = 3.0.0
Provides:       bundled(npm(style-mod)) = 4.1.3
Provides:       bundled(npm(tabbable)) = 6.4.0
Provides:       bundled(npm(tagged-tag)) = 1.0.0
Provides:       bundled(npm(tempusdominus-bootstrap-4)) = 5.39.2
Provides:       bundled(npm(tempusdominus-core)) = 5.19.3
Provides:       bundled(npm(throttle-debounce)) = 2.3.0
Provides:       bundled(npm(tiny-invariant)) = 1.3.3
Provides:       bundled(npm(tiny-warning)) = 1.0.3
Provides:       bundled(npm(to-regex-range)) = 5.0.1
Provides:       bundled(npm(toggle-selection)) = 1.0.6
Provides:       bundled(npm(tslib)) = 2.8.1
Provides:       bundled(npm(type-fest)) = 5.6.0
Provides:       bundled(npm(typed-styles)) = 0.0.7
Provides:       bundled(npm(undici-types)) = 6.21.0
Provides:       bundled(npm(uplot)) = 1.6.32
Provides:       bundled(npm(uplot-react)) = 1.2.4
Provides:       bundled(npm(use-callback-ref)) = 1.3.3
Provides:       bundled(npm(use-query-params)) = 2.2.2
Provides:       bundled(npm(use-sidecar)) = 1.1.3
Provides:       bundled(npm(use-sync-external-store)) = 1.6.0
Provides:       bundled(npm(value-equal)) = 1.0.1
Provides:       bundled(npm(w3c-keyname)) = 2.2.8
Provides:       bundled(npm(warning)) = 4.0.3
# END generated bundled npm Provides

%description
Prometheus is a monitoring system and time series database.

%prep
%goprep -p1
tar -xf %{S:1}
tar -xf %{S:2}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:3}

%build
%global gomodulesmode GO111MODULE=on
# Install frontend dependencies from package-local store. Lifecycle scripts stay
# disabled; required native tools are shipped as platform-specific npm packages.
export PATH="$PWD/.pnpm/node_modules/.bin:$PATH"
pnpm="$PWD/.pnpm/node_modules/.bin/pnpm"
pnpm_store="$PWD/.pnpm-store"
(cd web/ui && $pnpm install --offline --frozen-lockfile --ignore-scripts \
    --config.trust-lockfile=true --store-dir "$pnpm_store")
(cd web/ui/react-app && $pnpm install --offline --frozen-lockfile --ignore-scripts \
    --config.trust-lockfile=true --store-dir "$pnpm_store")
make ui-build
scripts/compress_assets.sh
# Keep build-only frontend dependencies and pnpm itself out of license payload discovery.
find web/ui -type d -name node_modules -prune -exec rm -rf -- {} +
rm -rf .pnpm .pnpm-store
export GOWORK=off
export GO_BUILDTAGS="builtinassets"
export GOFLAGS="-mod=vendor -buildvcs=false"
export GO_LDFLAGS="-X github.com/prometheus/common/version.Version=%{version}"
%gobuild -o %{gobuilddir}/bin/prometheus %{goipath}/cmd/prometheus
%gobuild -o %{gobuilddir}/bin/promtool %{goipath}/cmd/promtool

%install
%go_vendor_license_install -c %{S:3}
install -D -p -m 0755 %{gobuilddir}/bin/prometheus %{buildroot}%{_bindir}/prometheus
install -D -p -m 0755 %{gobuilddir}/bin/promtool %{buildroot}%{_bindir}/promtool

%check
%go_vendor_license_check -c %{S:3}
%if %{with check}
export GOWORK=off
# pprof debug routes are deliberately removed by Patch0.
skip_tests=(
    TestDebugHandler # asserts the upstream /debug/pprof endpoint returns HTTP 200
)
skip_pattern=$(IFS='|'; echo "${skip_tests[*]}")
%gotest -skip "${skip_pattern}" ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc README.md NOTICE
%{_bindir}/prometheus
%{_bindir}/promtool

%changelog
%autochangelog
