%bcond check 1

%global goipath github.com/dexidp/dex

Name:           dex
Version:        2.45.1
Release:        1%{?dist}
Summary:        OpenID Connect identity provider and OAuth 2.0 server

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0 AND Unicode-DFS-2016
URL:            https://github.com/dexidp/dex
Source0:        %{url}/archive/v%{version}/dex-%{version}.tar.gz
Source1:        dex-%{version}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

ExclusiveArch:  %{golang_arches_future}
BuildRequires:  go-vendor-tools
BuildRequires:  go-rpm-macros

%description
Dex is an identity service that uses OpenID Connect to drive authentication
for other apps. It acts as a portal to other identity providers through
connectors including LDAP, SAML 2.0, GitHub, Google, and more.

%prep
%autosetup -p1 -C
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export GO_LDFLAGS="-X main.version=v%{version}"
%gobuild -o dex ./cmd/dex

%install
%go_vendor_license_install -c %{S:2}
install -Dp -m 0755 ./dex -t %{buildroot}%{_bindir}

%check
%go_vendor_license_check -c %{S:2}
[[ "$(./dex version 2>&1)" == *"%{version}"* ]] || exit 1
%if %{with check}
%gotest $(go list ./... | grep -Ev 'connector/google|connector/saml|/server$')
%endif

%files -f %{go_vendor_license_filelist}
%license LICENSE
%doc README.md
%{_bindir}/dex

%changelog
%autochangelog
