# Generated by go2rpm 1.18.0

# https://github.com/anchore/syft
%global goipath         github.com/anchore/syft
Version:                1.42.4

%gometa -L -f


Name:           syft
Release:        0.1%{?dist}
Summary:        CLI tool and library for generating a Software Bill of Materials from container images and filesystems

# Generated by go-vendor-tools
License:        0BSD AND Apache-2.0 AND BSD-1-Clause AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND GPL-2.0-only AND ISC AND LicenseRef-Fedora-Public-Domain AND LicenseRef-scancode-unicode AND MIT AND MPL-2.0 AND (Apache-2.0 OR GPL-2.0-or-later)
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
CLI tool and library for generating a Software Bill of Materials from container
images and filesystems.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done


%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md
%{_bindir}/syft


%changelog
%autochangelog
