# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/fido-device-onboard/go-fdo-client
%global goipath         github.com/fido-device-onboard/go-fdo-client
%global with_debug 1

%if 0%{?with_debug}
%global _find_debuginfo_dwz_opts %{nil}
%global _dwz_low_mem_die_limit 0
%else
%global debug_package %{nil}
%endif

Version:        1.0.0
%gometa -L -f

Name:           go-fdo-client
Release:        2%{?dist}
Summary:        FIDO FDO compliant device on-boarding tool

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2

%description
go-fdo-client is the device-side implementation of FIDO Device Onboard
specification in Go. It provides an FDO client that interacts with
FDO manufacturer and owner servers to perform device on-boarding.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
#%%autopatch -p1

%build
%global gomodulesmode GO111MODULE=on

# https://discussion.fedoraproject.org/t/why-does-the-go-compiler-uses-x-nodwarf5-by-default/179804
# https://github.com/golang/go/issues/75079
export GOEXPERIMENT="nodwarf5"

export GO_LDFLAGS="-X %{goipath}/internal/version.VERSION=%{version}"
%gobuild -o %{gobuilddir}/bin/go-fdo-client %{goipath}

%install
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%if %{with check}
%gotest ./...
%endif

%files
%license LICENSE vendor/modules.txt
%doc README.md
%{_bindir}/go-fdo-client

%changelog
%autochangelog
