fetch:
  - type: git
    repo: "https://github.com/prometheus/prometheus"
    ref: "v${VERSION}"
    archive_name: "prometheus-${VERSION}.tar.gz"
  - type: url
    url: "https://github.com/prometheus/prometheus/releases/download/v${VERSION}/prometheus-web-ui-${VERSION}.tar.gz"
    filename: "prometheus-web-ui-${VERSION}.tar.gz"
  - type: vendor
    ecosystem: go
    archive_name: "prometheus-${VERSION}-vendor.tar.bz2"
    modules:
      - path: "."
        use_workspace: false
