#!/bin/bash
# update-bundled-provides.sh - Automate bundled dependency updates for golang package
#
# This script automates the workflow of extracting Go sources, running
# bundled-deps.sh, and updating the bundled provides section in golang.spec.
# It's designed to work both in Packit automation and as a manual tool for
# maintainers of this package. It's clearly not package agnostic. Please use
# with caution.
#
# Usage: ./update-bundled-provides.sh [SPEC_FILE]
#
# Copyright (C) 2026 Alejandro Sáez
# License: GPLv2+

set -euo pipefail

SPEC_FILE="${1:-golang.spec}"
MARKER="# Bundled/Vendored provides generated by bundled-deps.sh"

# Step 1: Check if sources are extracted by looking for modules.txt files
if ! find . -name "modules.txt" -type f 2>/dev/null | grep -q .; then
    echo "INFO: Sources not extracted, extracting now..."

    # Use fedpkg to download and extract sources
    # This handles the lookaside cache and source extraction properly
    if ! fedpkg sources 2>&1; then
        echo "ERROR: Failed to download sources with fedpkg sources"
        exit 1
    fi

    # Extract sources using fedpkg prep
    if ! fedpkg prep 2>&1; then
        echo "ERROR: Failed to extract sources with fedpkg prep"
        exit 1
    fi

    echo "INFO: Sources extracted successfully"
fi

# Step 2: Generate bundled provides (strip blank lines from output)
echo "INFO: Running bundled-deps.sh to generate provides..."
PROVIDES=$(./bundled-deps.sh | sed '/^$/d')

# Step 3: Validate output
if [ -z "$PROVIDES" ]; then
    echo "ERROR: bundled-deps.sh produced no output"
    exit 1
fi

if ! echo "$PROVIDES" | grep -q "Provides: bundled"; then
    echo "ERROR: bundled-deps.sh output does not contain 'Provides: bundled'"
    echo "Output was: $PROVIDES"
    exit 1
fi

# Step 4: Verify marker comment exists in spec file
if ! grep -q "$MARKER" "$SPEC_FILE"; then
    echo "ERROR: Marker comment not found in $SPEC_FILE"
    echo "Expected: $MARKER"
    exit 1
fi

# Step 5: Update spec file using awk to replace the bundled provides section
echo "INFO: Updating $SPEC_FILE with new bundled provides..."

TEMP_FILE=$(mktemp)

awk -v marker="$MARKER" -v provides="$PROVIDES" '
    BEGIN {
        in_section = 0
    }

    # When we find the marker, print it and the new provides
    $0 ~ marker {
        print marker " based on the in tree module data"
        print provides
        in_section = 1
        next
    }

    # Skip lines in the bundled provides section until we hit a blank line
    in_section && /^$/ {
        print ""
        in_section = 0
        next
    }

    # Skip other lines in the section
    in_section {
        next
    }

    # Print all other lines unchanged
    !in_section {
        print
    }
' "$SPEC_FILE" > "$TEMP_FILE"

# Verify the temp file is not empty
if [ ! -s "$TEMP_FILE" ]; then
    echo "ERROR: awk processing produced empty output"
    rm -f "$TEMP_FILE"
    exit 1
fi

# Verify the marker still exists in the output
if ! grep -q "$MARKER" "$TEMP_FILE"; then
    echo "ERROR: Marker comment lost during processing"
    rm -f "$TEMP_FILE"
    exit 1
fi

# Replace the spec file with the updated version
mv "$TEMP_FILE" "$SPEC_FILE"

# Count how many provides were added
PROVIDES_COUNT=$(echo "$PROVIDES" | wc -l)
echo "INFO: Successfully updated $SPEC_FILE with $PROVIDES_COUNT bundled provides"
