# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/mikefarah/yq
%global goipath         github.com/mikefarah/yq/v4
Version:                4.53.3

%gometa -L -f


Name:           yq
Release:        1%{?dist}
Summary:        Yq is a portable command-line YAML, JSON, XML, CSV, TOML, HCL  and properties processor

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT AND MPL-2.0 AND Unicode-3.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
Yq is a portable command-line YAML, JSON, XML, CSV, TOML, HCL  and properties
processor.

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/yq %{goipath}

%{gobuilddir}/bin/%{name} shell-completion bash > %{name}.bash
%{gobuilddir}/bin/%{name} shell-completion fish > %{name}.fish
%{gobuilddir}/bin/%{name} shell-completion zsh  > %{name}.zsh

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

install -Dpm 0644 %{name}.bash %{buildroot}%{bash_completions_dir}/%{name}
install -Dpm 0644 %{name}.fish %{buildroot}%{fish_completions_dir}/%{name}.fish
install -Dpm 0644 %{name}.zsh  %{buildroot}%{zsh_completions_dir}/_%{name}

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc examples CODE_OF_CONDUCT.md CONTRIBUTING.md README.md SECURITY.md
%doc how-it-works.md project-words.txt release_instructions.txt
%doc release_notes.txt
%{_bindir}/yq
%{bash_completions_dir}/%{name}
%{fish_completions_dir}/%{name}.fish
%{zsh_completions_dir}/_%{name}


%changelog
%autochangelog
