# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate archery

Name:           rust-archery
Version:        1.2.2
Release:        2.1%{?dist}
Summary:        Abstract over the atomicity of reference-counting pointers

License:        MIT
URL:            https://crates.io/crates/archery
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * remove criterion dependency
Patch:          archery-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Abstract over the atomicity of reference-counting pointers.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/release-notes.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fatal-warnings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fatal-warnings-devel %{_description}

This package contains library source intended for building other packages which
use the "fatal-warnings" feature of the "%{crate}" crate.

%files       -n %{name}+fatal-warnings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+triomphe-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+triomphe-devel %{_description}

This package contains library source intended for building other packages which
use the "triomphe" feature of the "%{crate}" crate.

%files       -n %{name}+triomphe-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
