# https://github.com/open-telemetry/opentelemetry-collector-releases
%global goipath         github.com/open-telemetry/opentelemetry-collector-releases/contrib
%global forgeurl        https://github.com/open-telemetry/opentelemetry-collector-releases
Version:                0.157.0

%gometa -L
%forgemeta

Name:           opentelemetry-collector-contrib
Release:        0.1%{?dist}
Summary:        OpenTelemetry Collector with community-contributed components

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MIT-0 AND MPL-2.0
URL:            https://github.com/open-telemetry/opentelemetry-collector-releases
Source0:        %{gosource}
# Source1/Source2 use explicit names (not %%{archivename}) because %%{archivename}
# expands to "opentelemetry-collector-releases-0.153.0" (the upstream repo name),
# while these archives are named after the package for clarity.
# Generated by OCB: go.mod, go.sum, main.go, components.go from
# distributions/otelcol-contrib/manifest.yaml — see create-vendor-tarball.sh
Source1:        opentelemetry-collector-contrib-%{version}-generated.tar.bz2
# Vendor archive: go_vendor_archive create is passed _build/ directly,
# so the archive has a bare vendor/ prefix. Extract inside pushd _build.
Source2:        opentelemetry-collector-contrib-%{version}-vendor.tar.bz2
Source3:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.23


%description
The OpenTelemetry Collector Contrib distribution includes all
community-contributed receivers, processors, exporters, extensions,
and connectors in addition to the core components.

This package provides the official otelcol-contrib binary from the
opentelemetry-collector-releases distribution, for ingesting telemetry
from diverse sources and forwarding to various backends.


%prep
%goprep -p1
# LICENSE lives at repo root; copy to OCB output dir for go_vendor_license
cp LICENSE _build/LICENSE
# OCB-generated sources (go.mod, go.sum, *.go) have no prefix;
# vendor archive also has bare prefix; extract both inside _build/
pushd _build
tar -xf %{S:1}
tar -xf %{S:2}
popd


%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:3}


%build
%global gomodulesmode GO111MODULE=on
pushd _build
%gobuild -o %{gobuilddir}/bin/otelcol-contrib .
popd


%install
# go_vendor_license runs from _build/ to scan only the OCB module,
# not the entire releases repo source tree
pushd _build
%go_vendor_license_install -c %{S:3}
popd
mv _build/licenses.list .

install -D -p -m 0755 %{gobuilddir}/bin/otelcol-contrib %{buildroot}%{_bindir}/otelcol-contrib

# upstream default config — taken directly from distributions/otelcol-contrib/ in Source0
install -D -p -m 0644 distributions/otelcol-contrib/config.yaml \
    %{buildroot}%{_sysconfdir}/otelcol-contrib/config.yaml


# No %%gocheck2: the OCB-generated _build/ module contains no *_test.go files.
# Tests for individual components run in their upstream module repositories.
%check
pushd _build
%go_vendor_license_check -c %{S:3}
popd


%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/otelcol-contrib
%config(noreplace) %{_sysconfdir}/otelcol-contrib/config.yaml


%changelog
%autochangelog
