# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/caddyserver/xcaddy
%global goipath         github.com/caddyserver/xcaddy
Version:                0.4.7

%gometa -L -f


Name:           xcaddy
Release:        0.1%{?dist}
Summary:        Build Caddy with plugins

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

Requires:       golang
Requires:       git-core

%description
Build Caddy with plugins.

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export LDFLAGS="-X %{goipath}/cmd.CustomVersion=v%{version}"
%gobuild -o %{gobuilddir}/bin/xcaddy %{goipath}/cmd/xcaddy

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
# Go 1.26 installs its FIPS module read-only under the temporary HOME used by
# this test, which prevents testing.TempDir from cleaning up the directory.
sed -i '/^func TestBuildHermeticEnv(t \*testing.T) {/a\	t.Skip("incompatible with the read-only Go FIPS module cache")' builder_test.go
%gotest -short ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/xcaddy


%changelog
%autochangelog
