# https://github.com/open-telemetry/opentelemetry-collector-releases
%global goipath         github.com/open-telemetry/opentelemetry-collector-releases/core
%global forgeurl        https://github.com/open-telemetry/opentelemetry-collector-releases
Version:                0.158.0

%gometa -L
%forgemeta

Name:           opentelemetry-collector
Release:        0.1%{?dist}
Summary:        OpenTelemetry Collector — vendor-neutral telemetry pipeline

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            https://github.com/open-telemetry/opentelemetry-collector-releases
Source0:        %{gosource}
# Source1/Source2 use explicit names (not %%{archivename}) because %%{archivename}
# expands to "opentelemetry-collector-releases-0.157.0" (the upstream repo name),
# while these archives are named after the package for clarity.
# Generated by OCB: go.mod, go.sum, main.go, components.go from
# distributions/otelcol/manifest.yaml — see create-vendor-tarball.sh
Source1:        opentelemetry-collector-%{version}-generated.tar.bz2
# Vendor archive: go_vendor_archive create is passed _build/ directly,
# so the archive has a bare vendor/ prefix. Extract inside pushd _build.
Source2:        opentelemetry-collector-%{version}-vendor.tar.bz2
Source3:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.24


%description
The OpenTelemetry Collector is a vendor-neutral agent for receiving,
processing, and exporting telemetry data (traces, metrics, logs).

This package provides the official otelcol binary from the
opentelemetry-collector-releases distribution, including:
  - Receivers: OTLP, Jaeger, Zipkin, Prometheus, host metrics, Kafka, no-op
  - Processors: batch, memory limiter, attributes, resource, span, filter,
                probabilistic sampler
  - Exporters: OTLP, OTLP/HTTP, debug, Prometheus, Prometheus remote write,
               file, Zipkin, Kafka, no-op
  - Extensions: health check, pprof, zPages, memory limiter


%prep
%goprep -p1
# LICENSE lives at repo root; copy to OCB output dir for go_vendor_license
cp LICENSE _build/LICENSE
# OCB-generated sources (go.mod, go.sum, *.go) have no prefix;
# vendor archive also has bare prefix; extract both inside _build/
pushd _build
tar -xf %{S:1}
tar -xf %{S:2}
popd


%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:3}


%build
%global gomodulesmode GO111MODULE=on
pushd _build
%gobuild -o %{gobuilddir}/bin/otelcol .
popd


%install
# go_vendor_license runs from _build/ to scan only the OCB module,
# not the entire releases repo source tree
pushd _build
%go_vendor_license_install -c %{S:3}
popd
mv _build/licenses.list .

install -D -p -m 0755 %{gobuilddir}/bin/otelcol %{buildroot}%{_bindir}/otelcol

# upstream default config — taken directly from distributions/otelcol/ in Source0
install -D -p -m 0644 distributions/otelcol/config.yaml %{buildroot}%{_sysconfdir}/otelcol/config.yaml


# No %%gocheck2: the OCB-generated _build/ module contains no *_test.go files.
# Tests for individual components run in their upstream module repositories.
%check
pushd _build
%go_vendor_license_check -c %{S:3}
popd


%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/otelcol
%config(noreplace) %{_sysconfdir}/otelcol/config.yaml


%changelog
%autochangelog
