# See the documentation for more information:
# https://packit.dev/docs/configuration/

copy_upstream_release_description: false

jobs:
- job: pull_from_upstream
  trigger: release
  dist_git_branches:
    - fedora-rawhide

- job: koji_build
  trigger: commit
  allowed_committers: ['packit']
  dist_git_branches:
    - fedora-rawhide
