%bcond check 1

%global goipath github.com/sigstore/cosign/v3

Name:           cosign
Version:        3.0.6
Release:        1%{?dist}
Summary:        Container signing, verification, and storage in an OCI registry

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND ISC AND MIT AND MIT-0 AND MPL-2.0
URL:            https://github.com/sigstore/cosign
Source0:        %{url}/archive/v%{version}/cosign-%{version}.tar.gz
Source1:        cosign-%{version}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

ExclusiveArch:  %{golang_arches_future}
BuildRequires:  go-vendor-tools
BuildRequires:  go-rpm-macros

%description
Cosign supports container signing, verification, and storage in an OCI
registry. It aims to make signatures invisible infrastructure.

%prep
%autosetup -p1 -C
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export LDFLAGS="-X sigs.k8s.io/release-utils/version.gitVersion=v%{version} \
    -X sigs.k8s.io/release-utils/version.gitTreeState=release"
%gobuild -o cosign ./cmd/cosign

%install
%go_vendor_license_install -c %{S:2}
install -Dp -m 0755 ./cosign -t %{buildroot}%{_bindir}

install -d %{buildroot}%{bash_completions_dir}
./cosign completion bash > %{buildroot}%{bash_completions_dir}/cosign
install -d %{buildroot}%{zsh_completions_dir}
./cosign completion zsh > %{buildroot}%{zsh_completions_dir}/_cosign
install -d %{buildroot}%{fish_completions_dir}
./cosign completion fish > %{buildroot}%{fish_completions_dir}/cosign.fish

%check
%go_vendor_license_check -c %{S:2}
[[ "$(./cosign version 2>&1)" == *"v%{version}"* ]] || exit 1
%if %{with check}
%gocheck2 -s TestGetRekorPubKeys -s TestVerifyEmbeddedSCT -s TestValidateAndUnpackCertWithSCT -s TestLoadCertsKeylessVerification -s TestGetCTLogPubKeys
%endif

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/cosign
%{bash_completions_dir}/cosign
%{zsh_completions_dir}/_cosign
%{fish_completions_dir}/cosign.fish

%changelog
%autochangelog
