# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/nats-io/nats-server
%global goipath         github.com/nats-io/nats-server/v2
%global forgeurl        https://github.com/nats-io/nats-server
Version:                2.12.12

%gometa -L -f


Name:           nats-server2.12
Release:        1.1%{?dist}
Summary:        High-performance server for NATS, the cloud and edge native messaging system

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

Source10:       nats-server2.12.conf
Source20:       nats-server2.12.service
Source21:       nats-server2.12.sysusers

BuildRequires:  go-vendor-tools
BuildRequires:  systemd-rpm-macros
BuildRequires:  procps-ng
%{?systemd_ordering}
%{?sysusers_requires_compat}

BuildRequires:  golang >= 1.25

Provides:       nats-server = %{version}-%{release}

%description
NATS is a connective technology built for the ever increasingly hyper-connected
world. It is a single technology that enables applications to securely
communicate across any combination of cloud vendors, on-premise, edge, web and
mobile, and devices. NATS consists of a family of open source products that are
tightly integrated but can be deployed easily and independently. NATS is being
used globally by thousands of companies, spanning use-cases including
microservices, edge computing, mobile, IoT and can be used for augmenting or
replacing traditional messaging.


%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/nats-server %{goipath}

%install
%go_vendor_license_install -c %{S:2}

install -D -p -m 0755 %{gobuilddir}/bin/nats-server %{buildroot}%{_bindir}/nats-server

# config
install -D -p -m 0644 %{S:10} %{buildroot}%{_sysconfdir}/nats-server/nats-server.conf

# systemd unit
install -D -p -m 0644 %{S:20} %{buildroot}%{_unitdir}/nats-server.service

# sysusers
install -D -p -m 0644 %{S:21} %{buildroot}%{_sysusersdir}/nats-server.conf

# data and log directories
install -d -m 0750 %{buildroot}%{_sharedstatedir}/nats-server
install -d -m 0750 %{buildroot}%{_localstatedir}/log/nats-server

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
# server/ integration tests create multi-node Raft clusters whose election
# timeouts (4-9s) fail to converge under mock's nspawn/overlayfs overhead.
# Upstream splits these across 15 CI jobs; we run server/* subpackages and
# the remaining unit-testable packages instead.
skip_tests=(
    TestSysLogger                   # requires a running syslog daemon
    TestOCSPPeerMonitor             # requires network access for OCSP responder
)
skip_pattern=$(IFS='|'; echo "${skip_tests[*]}")
%gotest -count=1 -p 1 -skip "${skip_pattern}" $(go list ./... | grep -v -E '/(server|test)$')
%endif

%pre
%sysusers_create_compat %{S:21}

%post
%systemd_post nats-server.service

%preun
%systemd_preun nats-server.service

%postun
%systemd_postun_with_restart nats-server.service


%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/nats-server
%{_unitdir}/nats-server.service
%{_sysusersdir}/nats-server.conf
%dir %{_sysconfdir}/nats-server
%config(noreplace) %{_sysconfdir}/nats-server/nats-server.conf
%attr(0750,nats,nats) %dir %{_sharedstatedir}/nats-server
%attr(0750,nats,nats) %dir %{_localstatedir}/log/nats-server


%changelog
%autochangelog
