# https://github.com/etcd-io/etcd
%global goipath         github.com/etcd-io/etcd
Version:                3.7.0

%gometa -L -f


Name:           etcd
Release:        0.1%{?dist}
Summary:        Distributed reliable key-value store for critical data of distributed systems

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools (per-submodule vendor tarballs)
Source1:        etcd-server-%{version}-vendor.tar.bz2
Source2:        etcd-etcdctl-%{version}-vendor.tar.bz2
Source3:        etcd-etcdutl-%{version}-vendor.tar.bz2
Source4:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
etcd is a distributed reliable key-value store for the most critical data
of a distributed system. It is used as the backing store for Kubernetes
and many other distributed systems.

%prep
%goprep -A
tar -xf %{S:1} -C server
tar -xf %{S:2} -C etcdctl
tar -xf %{S:3} -C etcdutl

%generate_buildrequires
pushd server > /dev/null
%go_vendor_license_buildrequires -c %{S:4}
popd > /dev/null

%build
%global gomodulesmode GO111MODULE=on GOWORK=off
export GO_LDFLAGS="-X go.etcd.io/etcd/api/v3/version.GitSHA=%{version}"
cd server
%gobuild -o %{gobuilddir}/bin/etcd .
cd ../etcdctl
%gobuild -o %{gobuilddir}/bin/etcdctl .
cd ../etcdutl
%gobuild -o %{gobuilddir}/bin/etcdutl .

%install
pushd server > /dev/null
%go_vendor_license_install -c %{S:4}
popd > /dev/null
mv server/licenses.list .
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
pushd server > /dev/null
%go_vendor_license_check -c %{S:4}
popd > /dev/null

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/etcd
%{_bindir}/etcdctl
%{_bindir}/etcdutl


%changelog
%autochangelog
