# Minimum required Java version is 11.
#export JAVA_HOME=/usr/lib/jvm/java-11

# Include here and not in JAVA_OPTS all options, that should only be used by Tomcat itself.
# Examples are heap size, GC logging, JMX ports etc.
#export CATALINA_OPTS="-Xmx512m -Xms256m"

# Java runtime options used when any command is executed.
#export JAVA_OPTS=""

# To enable remote debugging uncomment the following line.
# You will then be able to use a Java debugger on port 8000.
#export JAVA_OPTS="${JAVA_OPTS} -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"

# Java compiler to use for translating JavaServer Pages (JSPs). You can use all
# compilers that are accepted by Ant's build.compiler property.
#export JSP_COMPILER=javac
#export JAVA_OPTS="$JAVA_OPTS -Dbuild.compiler=$JSP_COMPILER"

# Enable the Java security manager? (true/false, default: false)
#export SECURITY_MANAGER=true