%bcond check 1

%global goipath github.com/oauth2-proxy/oauth2-proxy/v7

Name:           oauth2-proxy
Version:        7.15.3
Release:        0.1%{?dist}
Summary:        Reverse proxy providing authentication with OAuth2/OIDC providers

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND ISC AND MIT AND Unlicense
URL:            https://github.com/oauth2-proxy/oauth2-proxy
Source0:        %{url}/archive/v%{version}/oauth2-proxy-%{version}.tar.gz
Source1:        oauth2-proxy-%{version}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

ExclusiveArch:  %{golang_arches_future}
BuildRequires:  go-vendor-tools
BuildRequires:  go-rpm-macros

%description
OAuth2 Proxy is a reverse proxy that provides authentication with Google,
Azure, OpenID Connect, and many more identity providers.

%prep
%autosetup -p1 -C
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export GO_LDFLAGS="-X %{goipath}/pkg/version.VERSION=v%{version}"
%gobuild -o oauth2-proxy .

%install
%go_vendor_license_install -c %{S:2}
install -Dp -m 0755 ./oauth2-proxy -t %{buildroot}%{_bindir}

%check
%go_vendor_license_check -c %{S:2}
[[ "$(./oauth2-proxy --version 2>&1)" == *"%{version}"* ]] || exit 1
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/oauth2-proxy

%changelog
%autochangelog
