%bcond check 1

%global goipath go.k6.io/k6
Version: 1.7.1

%gometa -L

Name:           k6v1
Release:        0.1%{?dist}
Summary:        Modern load testing tool, version 1
# Generated by go-vendor-tools
License:        AGPL-3.0-only AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            https://github.com/grafana/k6
Source0:        https://github.com/grafana/k6/archive/refs/tags/v%{version}.tar.gz#/k6-%{version}.tar.gz
Source1:        go-vendor-tools.toml
Source2:        https://raw.githubusercontent.com/grafana/k6-cloud-openapi-client-go/97c96146fa7c3cf455a330c6c36cc69fdf6a43e5/LICENSE#/k6-cloud-openapi-client-go-LICENSE

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.25

Provides:       k6 = %{version}-%{release}
Conflicts:      k6v2

%description
Grafana k6 is an open-source load testing tool that makes performance testing
productive and accessible. This package follows the supported k6 version 1
release line.

%prep
%autosetup -p1 -n k6-%{version}
# These generated modules omitted their upstream license files when vendored.
install -D -p -m 0644 %{S:2} vendor/github.com/grafana/k6-cloud-openapi-client-go/LICENSE
install -D -p -m 0644 vendor/github.com/prometheus/client_model/LICENSE \
    vendor/buf.build/gen/go/prometheus/prometheus/protocolbuffers/go/LICENSE

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:1}

%build
%global gomodulesmode GO111MODULE=on
export GOFLAGS="-mod=vendor -buildvcs=false"
%gobuild -o %{gobuilddir}/bin/k6 %{goipath}

%install
%go_vendor_license_install -c %{S:1}
install -D -p -m 0755 %{gobuilddir}/bin/k6 %{buildroot}%{_bindir}/k6

%check
%go_vendor_license_check -c %{S:1}
%if %{with check}
# Integration packages and browser end-to-end tests require external runtimes.
skip_packages=(
    '/integration'
    '/internal/js/modules/k6/browser/tests$'
)
skip_package_pattern=$(IFS='|'; echo "${skip_packages[*]}")
# Keep exact unit-test exclusions here so failures remain visible and auditable.
skip_tests=(
    # Browser lifecycle timing is unreliable without a browser runtime.
    'TestBrowserRegistry'
    # Require resolver behavior unavailable in the isolated buildroot.
    'TestErrorCodes/(Unroutable|Unroutable_redirect)'
    'TestDnsResolve'
    # Go 1.26 reports PROTOCOL_ERROR before the test GOAWAY error code.
    'TestHTTP2GoAwayError'
)
skip_pattern=$(IFS='|'; echo "${skip_tests[*]}")
%gotest -p 1 ${skip_pattern:+-skip "${skip_pattern}"} $(go list ./... | grep -Ev "${skip_package_pattern}")
%endif

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/k6

%changelog
%autochangelog
