# https://github.com/distribution/distribution
%global goipath         github.com/distribution/distribution/v3
%global forgeurl        https://github.com/distribution/distribution
Version:                3.1.1

%gometa -L
%forgemeta


Name:           distribution
Release:        0.1%{?dist}
Summary:        Toolkit for storing and distributing container images and artifacts

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND ISC AND MIT AND MPL-2.0 AND Unlicense
URL:            %{gourl}
Source0:        %{gosource}
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
The distribution project provides an implementation of the OCI Distribution
Specification for storing and distributing container images and other content.

%prep
%goprep -A
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/registry ./cmd/registry

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%global test_ignores %{shrink:
    -s TestHTTPChecker
    -s TestConcurrentFileStreams
    -d registry/storage/driver/inmemory
}

%check
%go_vendor_license_check -c %{S:2}
%gocheck2 %{test_ignores}

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/registry


%changelog
%autochangelog
