# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/jaegertracing/jaeger
%global goipath         github.com/jaegertracing/jaeger
Version:                2.20.0

%gometa -L -f


Name:           jaeger
Release:        0.8%{?dist}
Summary:        CNCF Jaeger, a Distributed Tracing Platform

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MIT-0 AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Jaeger UI source matching the submodule pinned by this Jaeger release.
Source1:        https://github.com/jaegertracing/jaeger-ui/archive/v%{version}/jaeger-ui-%{version}.tar.gz
# Generated by go-vendor-tools
Source2:        %{archivename}-vendor.tar.bz2
Source3:        go-vendor-tools.toml
Source4:        0001-vendor-x-text-unicode-norm-fix-CVE-2026-56852.patch
Source5:        0002-vendor-bump-apache-thrift-0.24.0.patch
# pnpm CLI and architecture-neutral content-addressed store, populated by the update hook.
Source6:        jaeger-ui-pnpm-cache-%{version}.tar.bz2
Source7:        jaeger-ui-pnpm-cache.patch
# Bump bundled nanoid 5.1.15 -> 5.1.16 for CVE-2026-67214
Source8:        jaeger-ui-bump-nanoid-5.1.16.patch

# Bump ai-sidecar dependency pyasn1 to 0.6.4 for CVE fixes
Patch0:         fix-ai-sidecar-pyasn1-0.6.4.patch
# Bump ai-sidecar dependency joserfc to 1.7.2 for CVE-2026-62995
Patch1:         fix-ai-sidecar-joserfc-1.7.2.patch

BuildRequires:  go-vendor-tools
BuildRequires:  nodejs24
BuildRequires:  nodejs24-bin

# BEGIN generated bundled npm Provides
Provides:       bundled(npm(@ag-ui/client)) = 0.0.54
Provides:       bundled(npm(@ag-ui/core)) = 0.0.54
Provides:       bundled(npm(@ag-ui/encoder)) = 0.0.54
Provides:       bundled(npm(@ag-ui/proto)) = 0.0.54
Provides:       bundled(npm(@ant-design/colors)) = 8.0.1
Provides:       bundled(npm(@ant-design/cssinjs)) = 2.1.2
Provides:       bundled(npm(@ant-design/cssinjs-utils)) = 2.1.2
Provides:       bundled(npm(@ant-design/fast-color)) = 3.0.1
Provides:       bundled(npm(@ant-design/icons)) = 6.3.2
Provides:       bundled(npm(@ant-design/icons-svg)) = 4.5.0
Provides:       bundled(npm(@ant-design/react-slick)) = 2.0.0
Provides:       bundled(npm(@assistant-ui/core)) = 0.2.10
Provides:       bundled(npm(@assistant-ui/react)) = 0.14.14
Provides:       bundled(npm(@assistant-ui/react-ag-ui)) = 0.0.35
Provides:       bundled(npm(@assistant-ui/store)) = 0.2.13
Provides:       bundled(npm(@assistant-ui/tap)) = 0.5.14
Provides:       bundled(npm(@babel/runtime)) = 7.29.7
Provides:       bundled(npm(@bufbuild/protobuf)) = 2.12.1
Provides:       bundled(npm(@emotion/hash)) = 0.8.0
Provides:       bundled(npm(@emotion/unitless)) = 0.7.5
Provides:       bundled(npm(@floating-ui/core)) = 1.7.5
Provides:       bundled(npm(@floating-ui/dom)) = 1.7.6
Provides:       bundled(npm(@floating-ui/react-dom)) = 2.1.8
Provides:       bundled(npm(@floating-ui/utils)) = 0.2.11
Provides:       bundled(npm(@opentelemetry/api)) = 1.9.1
Provides:       bundled(npm(@opentelemetry/api-logs)) = 0.220.0
Provides:       bundled(npm(@opentelemetry/core)) = 2.8.0
Provides:       bundled(npm(@opentelemetry/core)) = 2.9.0
Provides:       bundled(npm(@opentelemetry/exporter-trace-otlp-http)) = 0.220.0
Provides:       bundled(npm(@opentelemetry/instrumentation)) = 0.220.0
Provides:       bundled(npm(@opentelemetry/instrumentation-document-load)) = 0.65.0
Provides:       bundled(npm(@opentelemetry/instrumentation-fetch)) = 0.220.0
Provides:       bundled(npm(@opentelemetry/otlp-exporter-base)) = 0.220.0
Provides:       bundled(npm(@opentelemetry/otlp-transformer)) = 0.220.0
Provides:       bundled(npm(@opentelemetry/resources)) = 2.9.0
Provides:       bundled(npm(@opentelemetry/sdk-logs)) = 0.220.0
Provides:       bundled(npm(@opentelemetry/sdk-metrics)) = 2.9.0
Provides:       bundled(npm(@opentelemetry/sdk-trace)) = 2.9.0
Provides:       bundled(npm(@opentelemetry/sdk-trace-base)) = 2.9.0
Provides:       bundled(npm(@opentelemetry/sdk-trace-web)) = 2.9.0
Provides:       bundled(npm(@opentelemetry/semantic-conventions)) = 1.43.0
Provides:       bundled(npm(@protobuf-ts/protoc)) = 2.11.1
Provides:       bundled(npm(@radix-ui/number)) = 1.1.2
Provides:       bundled(npm(@radix-ui/primitive)) = 1.1.4
Provides:       bundled(npm(@radix-ui/react-accessible-icon)) = 1.1.10
Provides:       bundled(npm(@radix-ui/react-accordion)) = 1.2.14
Provides:       bundled(npm(@radix-ui/react-alert-dialog)) = 1.1.17
Provides:       bundled(npm(@radix-ui/react-arrow)) = 1.1.10
Provides:       bundled(npm(@radix-ui/react-aspect-ratio)) = 1.1.10
Provides:       bundled(npm(@radix-ui/react-avatar)) = 1.2.0
Provides:       bundled(npm(@radix-ui/react-checkbox)) = 1.3.5
Provides:       bundled(npm(@radix-ui/react-collapsible)) = 1.1.14
Provides:       bundled(npm(@radix-ui/react-collection)) = 1.1.10
Provides:       bundled(npm(@radix-ui/react-compose-refs)) = 1.1.3
Provides:       bundled(npm(@radix-ui/react-context)) = 1.1.4
Provides:       bundled(npm(@radix-ui/react-context-menu)) = 2.3.1
Provides:       bundled(npm(@radix-ui/react-dialog)) = 1.1.17
Provides:       bundled(npm(@radix-ui/react-direction)) = 1.1.2
Provides:       bundled(npm(@radix-ui/react-dismissable-layer)) = 1.1.13
Provides:       bundled(npm(@radix-ui/react-dropdown-menu)) = 2.1.18
Provides:       bundled(npm(@radix-ui/react-focus-guards)) = 1.1.4
Provides:       bundled(npm(@radix-ui/react-focus-scope)) = 1.1.10
Provides:       bundled(npm(@radix-ui/react-form)) = 0.1.10
Provides:       bundled(npm(@radix-ui/react-hover-card)) = 1.1.17
Provides:       bundled(npm(@radix-ui/react-id)) = 1.1.2
Provides:       bundled(npm(@radix-ui/react-label)) = 2.1.10
Provides:       bundled(npm(@radix-ui/react-menu)) = 2.1.18
Provides:       bundled(npm(@radix-ui/react-menubar)) = 1.1.18
Provides:       bundled(npm(@radix-ui/react-navigation-menu)) = 1.2.16
Provides:       bundled(npm(@radix-ui/react-one-time-password-field)) = 0.1.10
Provides:       bundled(npm(@radix-ui/react-password-toggle-field)) = 0.1.5
Provides:       bundled(npm(@radix-ui/react-popover)) = 1.1.17
Provides:       bundled(npm(@radix-ui/react-popper)) = 1.3.1
Provides:       bundled(npm(@radix-ui/react-portal)) = 1.1.12
Provides:       bundled(npm(@radix-ui/react-presence)) = 1.1.6
Provides:       bundled(npm(@radix-ui/react-primitive)) = 2.1.6
Provides:       bundled(npm(@radix-ui/react-progress)) = 1.1.10
Provides:       bundled(npm(@radix-ui/react-radio-group)) = 1.4.1
Provides:       bundled(npm(@radix-ui/react-roving-focus)) = 1.1.13
Provides:       bundled(npm(@radix-ui/react-scroll-area)) = 1.2.12
Provides:       bundled(npm(@radix-ui/react-select)) = 2.3.1
Provides:       bundled(npm(@radix-ui/react-separator)) = 1.1.10
Provides:       bundled(npm(@radix-ui/react-slider)) = 1.4.1
Provides:       bundled(npm(@radix-ui/react-slot)) = 1.3.0
Provides:       bundled(npm(@radix-ui/react-switch)) = 1.3.1
Provides:       bundled(npm(@radix-ui/react-tabs)) = 1.1.15
Provides:       bundled(npm(@radix-ui/react-toast)) = 1.2.17
Provides:       bundled(npm(@radix-ui/react-toggle)) = 1.1.12
Provides:       bundled(npm(@radix-ui/react-toggle-group)) = 1.1.13
Provides:       bundled(npm(@radix-ui/react-toolbar)) = 1.1.13
Provides:       bundled(npm(@radix-ui/react-tooltip)) = 1.2.10
Provides:       bundled(npm(@radix-ui/react-use-callback-ref)) = 1.1.2
Provides:       bundled(npm(@radix-ui/react-use-controllable-state)) = 1.2.3
Provides:       bundled(npm(@radix-ui/react-use-effect-event)) = 0.0.3
Provides:       bundled(npm(@radix-ui/react-use-escape-keydown)) = 1.1.2
Provides:       bundled(npm(@radix-ui/react-use-is-hydrated)) = 0.1.1
Provides:       bundled(npm(@radix-ui/react-use-layout-effect)) = 1.1.2
Provides:       bundled(npm(@radix-ui/react-use-previous)) = 1.1.2
Provides:       bundled(npm(@radix-ui/react-use-rect)) = 1.1.2
Provides:       bundled(npm(@radix-ui/react-use-size)) = 1.1.2
Provides:       bundled(npm(@radix-ui/react-visually-hidden)) = 1.2.6
Provides:       bundled(npm(@radix-ui/rect)) = 1.1.2
Provides:       bundled(npm(@rc-component/async-validator)) = 6.0.0
Provides:       bundled(npm(@rc-component/cascader)) = 1.17.0
Provides:       bundled(npm(@rc-component/checkbox)) = 2.0.0
Provides:       bundled(npm(@rc-component/collapse)) = 1.2.0
Provides:       bundled(npm(@rc-component/color-picker)) = 3.1.1
Provides:       bundled(npm(@rc-component/context)) = 2.0.2
Provides:       bundled(npm(@rc-component/dialog)) = 1.10.0
Provides:       bundled(npm(@rc-component/drawer)) = 1.4.2
Provides:       bundled(npm(@rc-component/dropdown)) = 1.0.2
Provides:       bundled(npm(@rc-component/form)) = 1.8.5
Provides:       bundled(npm(@rc-component/image)) = 1.9.0
Provides:       bundled(npm(@rc-component/input)) = 1.3.1
Provides:       bundled(npm(@rc-component/input-number)) = 1.6.2
Provides:       bundled(npm(@rc-component/mentions)) = 1.10.0
Provides:       bundled(npm(@rc-component/menu)) = 1.4.1
Provides:       bundled(npm(@rc-component/mini-decimal)) = 1.1.4
Provides:       bundled(npm(@rc-component/motion)) = 1.3.3
Provides:       bundled(npm(@rc-component/mutate-observer)) = 2.0.1
Provides:       bundled(npm(@rc-component/notification)) = 2.0.7
Provides:       bundled(npm(@rc-component/overflow)) = 1.0.1
Provides:       bundled(npm(@rc-component/pagination)) = 1.4.0
Provides:       bundled(npm(@rc-component/picker)) = 1.11.0
Provides:       bundled(npm(@rc-component/portal)) = 2.2.1
Provides:       bundled(npm(@rc-component/progress)) = 1.0.2
Provides:       bundled(npm(@rc-component/qrcode)) = 2.0.0
Provides:       bundled(npm(@rc-component/rate)) = 1.0.1
Provides:       bundled(npm(@rc-component/resize-observer)) = 1.1.2
Provides:       bundled(npm(@rc-component/segmented)) = 1.3.0
Provides:       bundled(npm(@rc-component/select)) = 1.8.2
Provides:       bundled(npm(@rc-component/slider)) = 1.1.1
Provides:       bundled(npm(@rc-component/steps)) = 1.2.2
Provides:       bundled(npm(@rc-component/switch)) = 1.0.3
Provides:       bundled(npm(@rc-component/table)) = 1.10.2
Provides:       bundled(npm(@rc-component/tabs)) = 1.11.0
Provides:       bundled(npm(@rc-component/tooltip)) = 1.4.0
Provides:       bundled(npm(@rc-component/tour)) = 2.4.0
Provides:       bundled(npm(@rc-component/tree)) = 1.3.2
Provides:       bundled(npm(@rc-component/tree-select)) = 1.11.0
Provides:       bundled(npm(@rc-component/trigger)) = 3.9.1
Provides:       bundled(npm(@rc-component/upload)) = 1.1.1
Provides:       bundled(npm(@rc-component/util)) = 1.11.1
Provides:       bundled(npm(@rc-component/virtual-list)) = 1.2.0
Provides:       bundled(npm(@reduxjs/toolkit)) = 2.12.0
Provides:       bundled(npm(@rolldown/binding-android-arm64)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-darwin-arm64)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-darwin-x64)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-freebsd-x64)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-linux-arm-gnueabihf)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-linux-arm64-gnu)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-linux-arm64-musl)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-linux-ppc64-gnu)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-linux-s390x-gnu)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-linux-x64-gnu)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-linux-x64-musl)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-openharmony-arm64)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-win32-arm64-msvc)) = 1.1.0
Provides:       bundled(npm(@rolldown/binding-win32-x64-msvc)) = 1.1.0
Provides:       bundled(npm(@standard-schema/spec)) = 1.1.0
Provides:       bundled(npm(@standard-schema/utils)) = 0.3.0
Provides:       bundled(npm(@tanstack/query-core)) = 5.101.1
Provides:       bundled(npm(@tanstack/react-query)) = 5.101.1
Provides:       bundled(npm(@tanstack/react-virtual)) = 3.14.2
Provides:       bundled(npm(@tanstack/virtual-core)) = 3.17.0
Provides:       bundled(npm(@types/d3-array)) = 3.2.2
Provides:       bundled(npm(@types/d3-color)) = 3.1.3
Provides:       bundled(npm(@types/d3-ease)) = 3.0.2
Provides:       bundled(npm(@types/d3-interpolate)) = 3.0.4
Provides:       bundled(npm(@types/d3-path)) = 3.1.1
Provides:       bundled(npm(@types/d3-scale)) = 4.0.9
Provides:       bundled(npm(@types/d3-shape)) = 3.1.8
Provides:       bundled(npm(@types/d3-time)) = 3.0.4
Provides:       bundled(npm(@types/d3-timer)) = 3.0.2
Provides:       bundled(npm(@types/react)) = 19.2.7
Provides:       bundled(npm(@types/react-dom)) = 19.2.3
Provides:       bundled(npm(@types/use-sync-external-store)) = 0.0.6
Provides:       bundled(npm(@types/uuid)) = 10.0.0
Provides:       bundled(npm(@viz-js/viz)) = 3.28.0
Provides:       bundled(npm(acorn)) = 8.17.0
Provides:       bundled(npm(acorn-import-attributes)) = 1.9.5
Provides:       bundled(npm(antd)) = 6.5.0
Provides:       bundled(npm(aria-hidden)) = 1.2.6
Provides:       bundled(npm(assistant-cloud)) = 0.1.33
Provides:       bundled(npm(assistant-stream)) = 0.3.23
Provides:       bundled(npm(chance)) = 1.1.13
Provides:       bundled(npm(cjs-module-lexer)) = 2.2.0
Provides:       bundled(npm(classnames)) = 2.5.1
Provides:       bundled(npm(clsx)) = 2.1.1
Provides:       bundled(npm(combokeys)) = 3.0.1
Provides:       bundled(npm(compare-versions)) = 6.1.1
Provides:       bundled(npm(compute-scroll-into-view)) = 3.1.1
Provides:       bundled(npm(cookie)) = 1.1.1
Provides:       bundled(npm(copy-to-clipboard)) = 4.0.2
Provides:       bundled(npm(csstype)) = 3.2.3
Provides:       bundled(npm(d3-array)) = 3.2.4
Provides:       bundled(npm(d3-color)) = 3.1.0
Provides:       bundled(npm(d3-dispatch)) = 3.0.1
Provides:       bundled(npm(d3-drag)) = 3.0.0
Provides:       bundled(npm(d3-ease)) = 3.0.1
Provides:       bundled(npm(d3-flame-graph)) = 5.0.0
Provides:       bundled(npm(d3-format)) = 3.1.2
Provides:       bundled(npm(d3-hierarchy)) = 3.1.2
Provides:       bundled(npm(d3-interpolate)) = 3.0.1
Provides:       bundled(npm(d3-path)) = 3.1.0
Provides:       bundled(npm(d3-scale)) = 4.0.2
Provides:       bundled(npm(d3-selection)) = 3.0.0
Provides:       bundled(npm(d3-shape)) = 3.2.0
Provides:       bundled(npm(d3-time)) = 3.1.0
Provides:       bundled(npm(d3-time-format)) = 4.1.0
Provides:       bundled(npm(d3-timer)) = 3.0.1
Provides:       bundled(npm(d3-transition)) = 3.0.1
Provides:       bundled(npm(d3-zoom)) = 3.0.0
Provides:       bundled(npm(dayjs)) = 1.11.19
Provides:       bundled(npm(debug)) = 4.4.3
Provides:       bundled(npm(decimal.js-light)) = 2.5.1
Provides:       bundled(npm(decode-uri-component)) = 0.4.1
Provides:       bundled(npm(deep-freeze)) = 0.0.1
Provides:       bundled(npm(detect-node-es)) = 1.1.0
Provides:       bundled(npm(drange)) = 2.0.1
Provides:       bundled(npm(es-toolkit)) = 1.48.1
Provides:       bundled(npm(eventemitter3)) = 5.0.4
Provides:       bundled(npm(fast-json-patch)) = 3.1.1
Provides:       bundled(npm(filter-obj)) = 5.1.0
Provides:       bundled(npm(get-nonce)) = 1.0.1
Provides:       bundled(npm(immer)) = 11.1.8
Provides:       bundled(npm(import-in-the-middle)) = 3.2.0
Provides:       bundled(npm(internmap)) = 2.0.3
Provides:       bundled(npm(is-mobile)) = 5.0.0
Provides:       bundled(npm(isomorphic-fetch)) = 3.0.0
Provides:       bundled(npm(json2mq)) = 0.2.0
Provides:       bundled(npm(just-curry-it)) = 5.3.0
Provides:       bundled(npm(lodash)) = 4.18.1
Provides:       bundled(npm(logfmt)) = 1.4.0
Provides:       bundled(npm(lru-memoize)) = 1.1.0
Provides:       bundled(npm(markdown-to-jsx)) = 9.8.2
Provides:       bundled(npm(match-sorter)) = 8.3.0
Provides:       bundled(npm(memoize-one)) = 6.0.0
Provides:       bundled(npm(module-details-from-path)) = 1.0.4
Provides:       bundled(npm(ms)) = 2.1.3
Provides:       bundled(npm(nanoid)) = 5.1.16
Provides:       bundled(npm(node-fetch)) = 2.7.0
Provides:       bundled(npm(object-hash)) = 3.0.0
Provides:       bundled(npm(query-string)) = 9.4.0
Provides:       bundled(npm(radix-ui)) = 1.6.0
Provides:       bundled(npm(react)) = 19.2.0
Provides:       bundled(npm(react-circular-progressbar)) = 2.2.0
Provides:       bundled(npm(react-dom)) = 19.2.0
Provides:       bundled(npm(react-icons)) = 5.7.0
Provides:       bundled(npm(react-is)) = 18.3.1
Provides:       bundled(npm(react-is)) = 19.2.0
Provides:       bundled(npm(react-json-view-lite)) = 2.5.0
Provides:       bundled(npm(react-redux)) = 9.3.0
Provides:       bundled(npm(react-remove-scroll)) = 2.7.2
Provides:       bundled(npm(react-remove-scroll-bar)) = 2.3.8
Provides:       bundled(npm(react-router)) = 7.18.0
Provides:       bundled(npm(react-router-dom)) = 7.18.0
Provides:       bundled(npm(react-side-effect)) = 2.1.2
Provides:       bundled(npm(react-style-singleton)) = 2.2.3
Provides:       bundled(npm(react-textarea-autosize)) = 8.5.9
Provides:       bundled(npm(recharts)) = 3.9.1
Provides:       bundled(npm(reduce-reducers)) = 1.0.4
Provides:       bundled(npm(redux)) = 5.0.1
Provides:       bundled(npm(redux-actions)) = 3.0.3
Provides:       bundled(npm(redux-promise-middleware)) = 6.2.0
Provides:       bundled(npm(redux-thunk)) = 3.1.0
Provides:       bundled(npm(remove-accents)) = 0.5.0
Provides:       bundled(npm(require-in-the-middle)) = 8.0.1
Provides:       bundled(npm(reselect)) = 5.2.0
Provides:       bundled(npm(rxjs)) = 7.8.1
Provides:       bundled(npm(safe-content-frame)) = 0.0.20
Provides:       bundled(npm(scheduler)) = 0.27.0
Provides:       bundled(npm(scroll-into-view-if-needed)) = 3.1.0
Provides:       bundled(npm(secure-json-parse)) = 4.1.0
Provides:       bundled(npm(set-cookie-parser)) = 2.7.2
Provides:       bundled(npm(split)) = 0.2.10
Provides:       bundled(npm(split-on-first)) = 3.0.0
Provides:       bundled(npm(string-convert)) = 0.2.1
Provides:       bundled(npm(stylis)) = 4.4.0
Provides:       bundled(npm(throttle-debounce)) = 5.0.2
Provides:       bundled(npm(through)) = 2.3.8
Provides:       bundled(npm(tiny-invariant)) = 1.3.3
Provides:       bundled(npm(tr46)) = 0.0.3
Provides:       bundled(npm(tslib)) = 2.8.1
Provides:       bundled(npm(tween-functions)) = 1.2.0
Provides:       bundled(npm(u-basscss)) = 2.0.1
Provides:       bundled(npm(untruncate-json)) = 0.0.1
Provides:       bundled(npm(use-callback-ref)) = 1.3.3
Provides:       bundled(npm(use-composed-ref)) = 1.4.0
Provides:       bundled(npm(use-effect-event)) = 2.0.3
Provides:       bundled(npm(use-isomorphic-layout-effect)) = 1.2.1
Provides:       bundled(npm(use-latest)) = 1.3.0
Provides:       bundled(npm(use-sidecar)) = 1.1.3
Provides:       bundled(npm(use-sync-external-store)) = 1.6.0
Provides:       bundled(npm(uuid)) = 11.1.1
Provides:       bundled(npm(victory-vendor)) = 37.3.6
Provides:       bundled(npm(webidl-conversions)) = 3.0.1
Provides:       bundled(npm(whatwg-fetch)) = 3.6.20
Provides:       bundled(npm(whatwg-url)) = 5.0.0
Provides:       bundled(npm(zod)) = 3.25.76
Provides:       bundled(npm(zod)) = 4.4.2
Provides:       bundled(npm(zod)) = 4.4.3
Provides:       bundled(npm(zustand)) = 5.0.14
Provides:       bundled(npm(@jaegertracing/jaeger-ui)) = 2.20.0
Provides:       bundled(npm(@jaegertracing/plexus)) = 0.2.0
# END generated bundled npm Provides

%description
CNCF Jaeger, a Distributed Tracing Platform.

%prep
%goprep -p1
tar -xf %{S:2}
patch -p1 < %{S:4}
patch -p1 < %{S:5}
mkdir -p jaeger-ui
tar -xf %{S:1} -C jaeger-ui --strip-components=1
patch -d jaeger-ui -p1 < %{S:7}
patch -d jaeger-ui -p1 < %{S:8}
tar -xf %{S:6}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:3}

%build
%global gomodulesmode GO111MODULE=on
# Build UI from source using package-local store. Lifecycle scripts stay
# disabled; required native tools are shipped as platform-specific npm packages.
export PATH="$PWD/.pnpm/node_modules/.bin:$PATH"
pnpm="$PWD/.pnpm/node_modules/.bin/pnpm"
pnpm_store="$PWD/.pnpm-store"
(cd jaeger-ui && $pnpm install --offline --frozen-lockfile --ignore-scripts --store-dir "$pnpm_store")
(cd jaeger-ui && $pnpm run build)
make build-ui JAEGER_UI_DIR=jaeger-ui
# Keep build-only frontend dependencies and pnpm itself out of license payload discovery.
find jaeger-ui -type d -name node_modules -prune -exec rm -rf -- {} +
rm -rf .pnpm .pnpm-store

export LDFLAGS="-X github.com/jaegertracing/jaeger/internal/version.latestVersion=v%{version} -X github.com/jaegertracing/jaeger/internal/version.date=$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ) "
%gobuild -o %{gobuilddir}/bin/jaeger %{goipath}/cmd/jaeger

%install
%go_vendor_license_install -c %{S:3}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:3}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc CHANGELOG.md README.md SECURITY.md
%{_bindir}/jaeger


%changelog
%autochangelog
