# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/jaegertracing/jaeger
%global goipath         github.com/jaegertracing/jaeger
Version:                2.20.0

%gometa -L -f


Name:           jaeger
Release:        0.5%{?dist}
Summary:        CNCF Jaeger, a Distributed Tracing Platform

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MIT-0 AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Official, architecture-independent UI release assets. Jaeger's build-ui
# target compresses and embeds these files in the Go binary.
Source1:        https://github.com/jaegertracing/jaeger-ui/releases/download/v%{version}/assets.tar.gz#/jaeger-ui-assets-%{version}.tar.gz
# Generated by go-vendor-tools
Source2:        %{archivename}-vendor.tar.bz2
Source3:        go-vendor-tools.toml
Source4:        0001-vendor-x-text-unicode-norm-fix-CVE-2026-56852.patch
Source5:        0002-vendor-bump-apache-thrift-0.24.0.patch

# Bump ai-sidecar dependency pyasn1 to 0.6.4 for CVE fixes
Patch0:         fix-ai-sidecar-pyasn1-0.6.4.patch

BuildRequires:  go-vendor-tools

%description
CNCF Jaeger, a Distributed Tracing Platform.

%prep
%goprep -p1
tar -xf %{S:2}
patch -p1 < %{S:4}
patch -p1 < %{S:5}
mkdir -p jaeger-ui
tar -xf %{S:1} -C jaeger-ui

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:3}

%build
%global gomodulesmode GO111MODULE=on
make build-ui JAEGER_UI_DIR=jaeger-ui

export LDFLAGS="-X github.com/jaegertracing/jaeger/internal/version.latestVersion=v%{version} -X github.com/jaegertracing/jaeger/internal/version.date=$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ) "
%gobuild -o %{gobuilddir}/bin/jaeger %{goipath}/cmd/jaeger

%install
%go_vendor_license_install -c %{S:3}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:3}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc CHANGELOG.md README.md SECURITY.md
%{_bindir}/jaeger


%changelog
%autochangelog
