# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/jaegertracing/jaeger
%global goipath         github.com/jaegertracing/jaeger
Version:                2.19.0

%gometa -L -f


Name:           jaeger
Release:        1.1%{?dist}
Summary:        CNCF Jaeger, a Distributed Tracing Platform

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MIT-0 AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

# MCP extension tests bind to hardcoded port 16687; use localhost:0 instead
Patch0:         fix-mcp-test-port-binding.patch
# Bump ai-sidecar dependency pyasn1 to 0.6.4 for CVE fixes
Patch1:         fix-ai-sidecar-pyasn1-0.6.4.patch

BuildRequires:  go-vendor-tools

%description
CNCF Jaeger, a Distributed Tracing Platform.

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export LDFLAGS="-X github.com/jaegertracing/jaeger/internal/version.latestVersion=v%{version} "
%gobuild -o %{gobuilddir}/bin/jaeger %{goipath}/cmd/jaeger

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc CHANGELOG.md README.md SECURITY.md
%{_bindir}/jaeger


%changelog
%autochangelog
