%bcond check 1

%global goipath github.com/grafana/tempo
Version: 2.10.7

%gometa -L

Name:           tempo2.10
Release:        0.2%{?dist}
Summary:        High-volume distributed tracing backend
# Generated by go-vendor-tools
License:        AGPL-3.0-only AND Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND BSL-1.0 AND ISC AND MIT AND MPL-2.0 AND Unlicense
URL:            https://github.com/grafana/tempo
Source0:        https://github.com/grafana/tempo/archive/refs/tags/v%{version}.tar.gz#/tempo-%{version}.tar.gz
Source1:        go-vendor-tools.toml
Patch0:         0001-tests-use-explicit-loopback-addresses.patch
Patch1:         0002-livestore-treat-canceled-initial-offset-fetch-as-stop.patch
Patch2:         0003-vendor-bump-apache-thrift-0.24.0.patch

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.26

Provides:       tempo = %{version}-%{release}

%description
Grafana Tempo is a high-volume, minimal-dependency distributed tracing
backend. It is deeply integrated with Grafana, Prometheus, and Loki, and only
requires object storage to operate.

%prep
%autosetup -p1 -n tempo-%{version}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:1}

%build
%global gomodulesmode GO111MODULE=on
export GOFLAGS="-mod=vendor -buildvcs=false"
export GO_LDFLAGS="-X main.Version=%{version} -X main.Branch=rpm"
%gobuild -o %{gobuilddir}/bin/tempo %{goipath}/cmd/tempo

%install
%go_vendor_license_install -c %{S:1}
install -D -p -m 0755 %{gobuilddir}/bin/tempo %{buildroot}%{_bindir}/tempo
install -D -p -m 0644 tools/packaging/tempo.yaml %{buildroot}%{_sysconfdir}/tempo/config.yml

%check
%go_vendor_license_check -c %{S:1}
%if %{with check}
# Integration packages orchestrate Docker containers and cannot run in mock.
# Run every unit-testable package instead.
skip_packages=(
    '/integration'
)
skip_package_pattern=$(IFS='|'; echo "${skip_packages[*]}")
skip_tests=(
    TestMemcachedJumpHashSelector_PickSever # performs live DNS resolution
    TestApp_RunStop # requires loopback HTTP connectivity in the isolated build namespace
)
skip_pattern=$(IFS='|'; echo "${skip_tests[*]}")
%gotest -skip "${skip_pattern}" $(go list ./... | grep -Ev "${skip_package_pattern}")
%endif

%files -f %{go_vendor_license_filelist}
%doc CHANGELOG.md README.md
%{_bindir}/tempo
%dir %{_sysconfdir}/tempo
%config(noreplace) %{_sysconfdir}/tempo/config.yml

%changelog
%autochangelog
