# Generated by go2rpm 1.19.0

# https://github.com/anchore/grype
%global goipath         github.com/anchore/grype
Version:                0.115.0

%gometa -L -f


Name:           grype
Release:        0.2%{?dist}
Summary:        Vulnerability scanner for container images and filesystems

# Generated by go-vendor-tools
License:        0BSD AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND ISC AND LicenseRef-Fedora-Public-Domain AND MIT AND MPL-2.0 AND Unlicense AND (Apache-2.0 OR GPL-2.0-or-later)
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
A vulnerability scanner for container images and filesystems.

Grype finds vulnerabilities in OS packages and language ecosystem packages,
and supports SBOM attestation scanning.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export GO_LDFLAGS="-X main.version=%{version}"
%gobuild -o %{gobuilddir}/bin/grype %{goipath}/cmd/grype

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/grype


%changelog
%autochangelog
