---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/block-releases: 'false'
    pp.engineering.redhat.com/business-unit: rhel-platforms
  name: hummingbird-rpms-private-nodejs20
  namespace: rhtap-releng-tenant
spec:
  applications:
    - private-nodejs20-rpms-main
  data:
    intention: production
    pulp:
      domain: private-hummingbird-nodejs20-unsigned
      secretName: hummingbird-pulp-credentials-private-production-secret
    signOptions:
      signKeytab:
        principal: "konflux-release-signing-prod@IPA.REDHAT.COM"
        name: "keytab"
        secret: "konflux-release-signing-prod-sa"
      signPipelineImage: "quay.io/konflux-ci/signing:latest"
      signPipelineServiceAccount: "signing-pipeline-sa"
      skipUploadToPulp: true
      artifactStorageSecret: "signing-artifact-storage-prod"
      signKeyAlias:
        key: "release4,release2,ima"
      unsignedRpmsDomain: private-hummingbird-nodejs20-unsigned
      signedRpmsDomain: private-hummingbird-nodejs20
    releaseNotes:
      product_id: [1071]
      product_name: "Red Hat Hardened Images"
      product_version: "1"
      # note: these fields are generated by the
      #       convertyaml collector
      # solution:
      # synopsis:
      # topic:
      # description:
      #
    singleComponentMode: true
    sign:
      configMapName: hacbs-signing-pipeline-config-staging-e2e
      cosignSecretName: konflux-cosign-signing-stage
    pyxis:
      secret: pyxis-staging-secret
      server: stage
    atlas:
      server: stage
    mapping:
      rpm-repositories:
        - name: x86_64
          arch: x86_64
          repository_id: private-hummingbird-nodejs20-x86_64-rpms
          repository_name: x86_64
          distro: hummingbird-20251124
        - name: aarch64
          arch: aarch64
          repository_id: private-hummingbird-nodejs20-aarch64-rpms
          repository_name: aarch64
          distro: hummingbird-20251124
        - name: src
          arch: src
          repository_id: private-hummingbird-nodejs20-source-rpms
          repository_name: source
          distro: hummingbird-20251124
        # leaving this here for backwards compatibility before HUM-808
        - name: source
          arch: source
          repository_id: private-hummingbird-nodejs20-source-rpms
          repository_name: source
          distro: hummingbird-20251124
      defaults:
        pushSourceContainer: true
      components:
        - name: nodejs20-lts-main
          contentType: rpm
  origin: hummingbird-tenant
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: https://github.com/konflux-ci/release-service-catalog.git
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/managed/push-rpms-to-pulp/push-rpms-to-pulp.yaml"
      resolver: git
    taskRunSpecs:
      - pipelineTaskName: populate-release-notes
        stepSpecs:
          - computeResources:
              limits:
                cpu: '1'
                memory: 256Mi
              requests:
                cpu: '1'
                memory: 256Mi
            name: populate-release-notes-artifacts
      - pipelineTaskName: upload-src-rpm-sbom-attestation
        stepSpecs:
          - computeResources:
              limits:
                memory: 1Gi
              requests:
                cpu: '1'
                memory: 1Gi
            name: upload
        # increase limits for verify-conforma to 8Gi memory and 2 cpu
        # that is needed for rust
      - pipelineTaskName: verify-conforma
        stepSpecs:
          - computeResources:
              limits:
                cpu: '2'
                memory: 8Gi
              requests:
                cpu: '2'
                memory: 8Gi
            name: validate
    serviceAccountName: hummingbird-rpm-release-staging
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: rpm-hummingbird-stage
