%bcond check 1

# https://github.com/spiffe/spire
%global goipath         github.com/spiffe/spire
%global forgeurl        https://github.com/spiffe/spire
Version:                1.14.7

%gometa -L
%forgemeta


Name:           spire1.14
Release:        0.1%{?dist}
Summary:        The SPIFFE Runtime Environment

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND ISC AND MIT AND MIT-0 AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

# example configs, authored for FHS paths (upstream conf/{server,agent} are
# dev fixtures with /tmp paths and dummy CA files, not shippable as-is)
Source10:       server.conf
Source11:       agent.conf
Source12:       oidc-discovery-provider.conf

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.26

%description
SPIRE (the SPIFFE Runtime Environment) is a toolchain of APIs for
establishing trust between software systems across a wide variety of
hosting platforms. SPIRE exposes the SPIFFE Workload API, which can attest
running software systems and issue SPIFFE IDs and SVIDs to them.

This base package only provides shared license and documentation files.
Install spire1.14-server, spire1.14-agent, and/or
spire1.14-oidc-discovery-provider for the actual binaries.


%package server
Summary:        SPIRE Server
Requires:       %{name} = %{version}-%{release}

%description server
The SPIRE Server is responsible for managing and signing identity
documents, as well as maintaining a registry of SPIFFE IDs and the
attestation policies associated with them.


%package agent
Summary:        SPIRE Agent
Requires:       %{name} = %{version}-%{release}

%description agent
The SPIRE Agent runs on every node and exposes the Workload API, which
attests and issues SPIFFE identities to workloads on the node.


%package oidc-discovery-provider
Summary:        SPIRE OIDC Discovery Provider
Requires:       %{name} = %{version}-%{release}

%description oidc-discovery-provider
The SPIRE OIDC Discovery Provider is a small helper that exposes a JSON
Web Key Set (JWKS) for JWT-SVID validation via a minimal OIDC discovery
document.


%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}


%build
%global gomodulesmode GO111MODULE=on
export GO_LDFLAGS="-X %{goipath}/pkg/common/version.gittag=%{version}"
%gobuild -o %{gobuilddir}/bin/spire-server %{goipath}/cmd/spire-server
%gobuild -o %{gobuilddir}/bin/spire-agent %{goipath}/cmd/spire-agent
%gobuild -o %{gobuilddir}/bin/oidc-discovery-provider %{goipath}/support/oidc-discovery-provider


%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd %{buildroot}%{_bindir}
install -m 0755 -vd %{buildroot}%{_sysconfdir}/spire

# server
install -m 0755 -vp %{gobuilddir}/bin/spire-server %{buildroot}%{_bindir}/
install -m 0755 -vd %{buildroot}%{_sysconfdir}/spire/server
install -m 0644 -vp %{S:10} %{buildroot}%{_sysconfdir}/spire/server/server.conf
install -m 0750 -vd %{buildroot}%{_sharedstatedir}/spire/server

# agent
install -m 0755 -vp %{gobuilddir}/bin/spire-agent %{buildroot}%{_bindir}/
install -m 0755 -vd %{buildroot}%{_sysconfdir}/spire/agent
install -m 0644 -vp %{S:11} %{buildroot}%{_sysconfdir}/spire/agent/agent.conf
install -m 0750 -vd %{buildroot}%{_sharedstatedir}/spire/agent

# oidc-discovery-provider
install -m 0755 -vp %{gobuilddir}/bin/oidc-discovery-provider %{buildroot}%{_bindir}/
install -m 0755 -vd %{buildroot}%{_sysconfdir}/spire/oidc-discovery-provider
install -m 0644 -vp %{S:12} %{buildroot}%{_sysconfdir}/spire/oidc-discovery-provider/oidc-discovery-provider.conf
install -m 0750 -vd %{buildroot}%{_sharedstatedir}/spire/oidc-discovery-provider


%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
# TestExitDetection spawns and signals a real child process, which is flaky
# (process reaping/timing) under mock's sandboxed, resource-constrained
# parallel test execution rather than a real functional failure.
for test in "TestExitDetection"; do
    awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled flaky test\")"; next}1' \
        $(grep -rl "func $test(" pkg/common/peertracker)
done

# Packages that can't pass in a sandboxed build: tpmdevid needs the
# go-tpm-tools cgo TPM simulator (missing Platform.h, a git-submodule file
# `go mod vendor` doesn't pull in); docker/k8s workloadattestor sigstore
# subtests need network access to refresh TUF root metadata; cli/run spawns
# and waits on a real spire-server process, which is flaky under mock's
# resource-constrained parallel test execution.
check_excludes=(
    '/nodeattestor/tpmdevid'
    '/workloadattestor/docker$'
    '/workloadattestor/k8s$'
    '/cmd/spire-server/cli/run$'
)
check_exclude_pattern=$(IFS='|'; echo "${check_excludes[*]}")
%gotest $(go list ./pkg/... ./cmd/... ./support/... | grep -Ev "$check_exclude_pattern")
%endif


%files -f %{go_vendor_license_filelist}
%doc README.md CHANGELOG.md


%files server
%{_bindir}/spire-server
%dir %{_sysconfdir}/spire
%dir %{_sysconfdir}/spire/server
%config(noreplace) %{_sysconfdir}/spire/server/server.conf
%dir %{_sharedstatedir}/spire
%dir %{_sharedstatedir}/spire/server


%files agent
%{_bindir}/spire-agent
%dir %{_sysconfdir}/spire
%dir %{_sysconfdir}/spire/agent
%config(noreplace) %{_sysconfdir}/spire/agent/agent.conf
%dir %{_sharedstatedir}/spire
%dir %{_sharedstatedir}/spire/agent


%files oidc-discovery-provider
%{_bindir}/oidc-discovery-provider
%dir %{_sysconfdir}/spire
%dir %{_sysconfdir}/spire/oidc-discovery-provider
%config(noreplace) %{_sysconfdir}/spire/oidc-discovery-provider/oidc-discovery-provider.conf
%dir %{_sharedstatedir}/spire
%dir %{_sharedstatedir}/spire/oidc-discovery-provider


%changelog
%autochangelog
