# https://github.com/kubernetes/git-sync
%global goipath         k8s.io/git-sync
%global forgeurl        https://github.com/kubernetes/git-sync
Version:                4.4.0

%gometa -L
%forgemeta


Name:           git-sync
Release:        0.1%{?dist}
Summary:        Sidecar container that clones and watches a git repository

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

Requires:       git-core
Requires:       openssh-clients
Requires:       ca-certificates

%description
git-sync is a sidecar container and command-line tool that pulls a git
repository into a local directory. It can be used to synchronize
configuration files, scripts, or any other content stored in git.

%prep
%goprep -A
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export GO_LDFLAGS="-X k8s.io/git-sync/pkg/version.VERSION=v%{version}"
%gobuild -o %{gobuilddir}/bin/git-sync .

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%gotest ./...

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/git-sync


%changelog
%autochangelog
