# https://github.com/open-telemetry/opentelemetry-collector-releases
%global goipath         github.com/open-telemetry/opentelemetry-collector-releases/k8s
%global forgeurl        https://github.com/open-telemetry/opentelemetry-collector-releases
Version:                0.160.0

%gometa -L
%forgemeta

Name:           opentelemetry-collector-k8s
Release:        0.1%{?dist}
Summary:        OpenTelemetry Collector for Kubernetes

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            https://github.com/open-telemetry/opentelemetry-collector-releases
Source0:        %{gosource}
# Generated by OCB from distributions/otelcol-k8s/manifest.yaml.
Source1:        opentelemetry-collector-k8s-%{version}-generated.tar.bz2
# Vendor archive has a bare vendor/ prefix and is extracted inside _build.
Source2:        opentelemetry-collector-k8s-%{version}-vendor.tar.bz2
Source3:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.24


%description
The OpenTelemetry Collector Kubernetes distribution is designed to monitor
Kubernetes clusters and services running in Kubernetes. It provides a curated
subset of core and community components, including Kubernetes receivers,
processors, discovery, and persistent file storage.

This package provides the official otelcol-k8s binary generated from the
opentelemetry-collector-releases Kubernetes distribution manifest.


%prep
%goprep -p1
cp LICENSE _build/LICENSE
pushd _build
tar -xf %{S:1}
tar -xf %{S:2}
popd


%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:3}


%build
%global gomodulesmode GO111MODULE=on
pushd _build
%gobuild -o %{gobuilddir}/bin/otelcol-k8s .
popd


%install
pushd _build
%go_vendor_license_install -c %{S:3}
popd
mv _build/licenses.list .

install -D -p -m 0755 %{gobuilddir}/bin/otelcol-k8s %{buildroot}%{_bindir}/otelcol-k8s


# No %%gocheck2: the OCB-generated _build/ module contains no *_test.go files.
# Tests for individual components run in their upstream module repositories.
%check
pushd _build
%go_vendor_license_check -c %{S:3}
popd


%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/otelcol-k8s


%changelog
%autochangelog
