%bcond check 1

%global goipath github.com/sigstore/fulcio

Name:           fulcio
Version:        1.8.8
Release:        0.1%{?dist}
Summary:        Sigstore OIDC certificate authority for code signing

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            https://github.com/sigstore/fulcio
Source0:        %{url}/archive/v%{version}/fulcio-%{version}.tar.gz
Source1:        fulcio-%{version}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

ExclusiveArch:  %{golang_arches_future}
BuildRequires:  go-vendor-tools
BuildRequires:  go-rpm-macros

%description
Fulcio is a certificate authority that issues short-lived code signing
certificates for OpenID Connect identities as part of the Sigstore project.

%prep
%autosetup -p1 -C
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export LDFLAGS="-X sigs.k8s.io/release-utils/version.gitVersion=v%{version} \
    -X sigs.k8s.io/release-utils/version.gitTreeState=release"
%gobuild -o fulcio-server .

%install
%go_vendor_license_install -c %{S:2}
install -Dp -m 0755 ./fulcio-server %{buildroot}%{_bindir}/fulcio-server

%check
%go_vendor_license_check -c %{S:2}
[[ "$(./fulcio-server version 2>&1)" == *"v%{version}"* ]] || exit 1
%if %{with check}
%gocheck2
%endif

%files -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/fulcio-server

%changelog
%autochangelog
