%bcond check 1

%global goipath github.com/sigstore/rekor

Name:           rekor
Version:        1.5.4
Release:        0.1%{?dist}
Summary:        Software supply chain transparency log (Rekor)

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND CDDL-1.0 AND ISC AND LicenseRef-Fedora-Public-Domain AND MIT AND MPL-2.0
URL:            https://github.com/sigstore/rekor
Source0:        %{url}/archive/v%{version}/rekor-%{version}.tar.gz
Source1:        rekor-%{version}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

ExclusiveArch:  %{golang_arches_future}
BuildRequires:  go-vendor-tools
BuildRequires:  go-rpm-macros

%description
Rekor is a software supply chain transparency log providing an immutable,
tamper-resistant ledger of signed software metadata backed by a Trillian
transparency log.

%package server
Summary:        REST API server for the Rekor transparency log

%description server
rekor-server is the REST API server component of Rekor. It accepts and
serves signed metadata records backed by a Trillian transparency log.

%prep
%autosetup -p1 -C
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export LDFLAGS="-X sigs.k8s.io/release-utils/version.gitVersion=v%{version} \
    -X sigs.k8s.io/release-utils/version.gitTreeState=release"
%gobuild -o rekor-server ./cmd/rekor-server

%install
%go_vendor_license_install -c %{S:2}
install -Dp -m 0755 ./rekor-server -t %{buildroot}%{_bindir}

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files server -f %{go_vendor_license_filelist}
%doc README.md
%{_bindir}/rekor-server

%changelog
%autochangelog
