# Adapted from Kubernetes repository and kubeadm documentation
# Any changes made here will be overwritten when next version is
# installed. To override, place systemd file with needed changes
# in /etc/systemd/system/kubelet.service.d/ (not in /usr/lib/systemd/system/kubelet.service.d/).
# See: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"

# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env

# Copied from upstream
# This is a file that the user can use for overrides of the kubelet args as a last
# resort. The preferred method is to set the .NodeRegistration.KubeletExtraArgsi
# object in the configuration files instead.
# KUBELET_EXTRA_ARGS is sourced from this file.
EnvironmentFile=-/etc/sysconfig/kubelet


ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
