%bcond check 1

Name:           golist
Version:        0.11.0
Release:        1.1%{?dist}
Summary:        A tool to analyse the properties of a Go (Golang) codebase
# Generated by go-vendor-tools
License:        BSD-2-Clause AND BSD-3-Clause AND MIT
URL:            https://forge.fedoraproject.org/go/golist
Source0:        %{url}/archive/v%{version}.tar.gz#/golist-%{version}.tar.gz
# Generated by go-vendor-tools
Source1:        golist-%{version}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

ExclusiveArch:  %{golang_arches}
BuildRequires:  go-vendor-tools
BuildRequires:  go-rpm-macros

%description
A tool to analyse the properties of a Go (Golang) codebase.

%prep
%autosetup -p1 -C
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o golist ./cmd/golist

%install
%go_vendor_license_install -c %{S:2}
install -Dp ./golist -t %{buildroot}%{_bindir}

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gocheck2
%endif

%files -f %{go_vendor_license_filelist}
%doc NEWS.md README.md
%{_bindir}/golist

%changelog
%autochangelog
