# NATS Server Configuration
# See https://docs.nats.io/running-a-nats-service/configuration

listen: 0.0.0.0:4222

jetstream {
    store_dir: /var/lib/nats-server/jetstream
}

pid_file: /run/nats-server/nats-server.pid
