%bcond check 1

%global goipath github.com/grafana/loki/v3
Version: 3.7.7

%gometa -L

Name:           loki3.7
Release:        0.1%{?dist}
Summary:        Horizontally scalable log aggregation system
# Generated by go-vendor-tools
License:        AGPL-3.0-only AND Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND BSL-1.0 AND ISC AND MIT AND MIT-0 AND MPL-2.0 AND Unlicense
URL:            https://github.com/grafana/loki
Source0:        https://github.com/grafana/loki/archive/refs/tags/v%{version}.tar.gz#/loki-%{version}.tar.gz
Source1:        go-vendor-tools.toml
Patch0:         0001-tests-use-explicit-loopback-addresses.patch
# Update the encoding/json error type name used by Go 1.27.
Patch1:         0002-tests-update-json-error-for-go1.27.patch

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.26

Provides:       loki = %{version}-%{release}

%description
Grafana Loki is a horizontally scalable, highly available, multi-tenant log
aggregation system inspired by Prometheus. It indexes metadata about logs and
stores compressed log data in object storage.

%package logcli
Summary:        Command-line client for Grafana Loki
Provides:       logcli = %{version}-%{release}

%description logcli
LogCLI is a command-line client for querying and interacting with Grafana Loki.

%package canary
Summary:        Canary application for Grafana Loki
Provides:       loki-canary = %{version}-%{release}

%description canary
Loki Canary writes synthetic log entries and verifies that Grafana Loki can
ingest and query them.

%prep
%autosetup -p1 -n loki-%{version}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:1}

%build
%global gomodulesmode GO111MODULE=on
export GOFLAGS="-mod=vendor -buildvcs=false"
export GO_LDFLAGS="-X %{goipath}/pkg/util/build.Version=%{version} -X %{goipath}/pkg/util/build.Branch=rpm"
%gobuild -o %{gobuilddir}/bin/loki %{goipath}/cmd/loki
%gobuild -o %{gobuilddir}/bin/logcli %{goipath}/cmd/logcli
%gobuild -o %{gobuilddir}/bin/loki-canary %{goipath}/cmd/loki-canary

%install
%go_vendor_license_install -c %{S:1}
install -D -p -m 0755 %{gobuilddir}/bin/loki %{buildroot}%{_bindir}/loki
install -D -p -m 0755 %{gobuilddir}/bin/logcli %{buildroot}%{_bindir}/logcli
install -D -p -m 0755 %{gobuilddir}/bin/loki-canary %{buildroot}%{_bindir}/loki-canary
install -D -p -m 0644 cmd/loki/loki-local-config.yaml %{buildroot}%{_sysconfdir}/loki/config.yml

%check
%go_vendor_license_check -c %{S:1}
%if %{with check}
# Some tests create fixed-name working files beneath os.TempDir. Keep them in
# the package build tree so retained mock state cannot cause ownership clashes.
export TMPDIR="${PWD}/.test-tmp"
mkdir -p "${TMPDIR}"
# Integration packages require external services or container orchestration.
# Keep exact unit-test exclusions here so failures remain visible and auditable.
skip_packages=(
    '/integration'
)
skip_package_pattern=$(IFS='|'; echo "${skip_packages[*]}")
skip_tests=(
    Test_TargetManager # asynchronous Docker log transfer can duplicate entries
    'TestProxyEndpoint_QuerySplitting/query_spans_threshold_\(split_and_merge\)' # clock-sensitive threshold classification
    'Test_BuilderLoop/exceed_max_retries' # races asynchronous retry accounting
    TestTablesManager_TableLocking        # timing-sensitive lock expiry assertions
)
skip_pattern=$(IFS='|'; echo "${skip_tests[*]}")
%gotest ${skip_pattern:+-skip "${skip_pattern}"} $(go list ./... | grep -Ev "${skip_package_pattern}")
%endif

%files -f %{go_vendor_license_filelist}
%doc CHANGELOG.md README.md
%{_bindir}/loki
%dir %{_sysconfdir}/loki
%config(noreplace) %{_sysconfdir}/loki/config.yml

%files logcli -f %{go_vendor_license_filelist}
%doc CHANGELOG.md README.md
%{_bindir}/logcli

%files canary -f %{go_vendor_license_filelist}
%doc CHANGELOG.md README.md
%{_bindir}/loki-canary

%changelog
%autochangelog
