# Generated by go2rpm 1.18.0
%bcond check 1

%global git_commit 0707f566a3f4ced24009ef14d67fe0ce69db4be9
%global k8s_major 1
%global k8s_minor 34

# https://github.com/helm/helm
%global goipath         helm.sh/helm/v3
%global forgeurl        https://github.com/helm/helm
Version:                3.21.4

%gometa -L -f

Name:           helm3
Release:        0.1%{?dist}
Summary:        The Kubernetes Package Manager

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml
Patch0:         CVE-2026-63308-files-lines-empty-file.patch

Provides:       helm = %{version}-%{release}

Obsoletes:      golang-helm-3 < 3.11.1-6
Obsoletes:      golang-helm-3-devel < 3.11.1-6

BuildRequires:  go-vendor-tools

%description
Helm is a tool for managing Charts. Charts are packages of pre-configured
Kubernetes resources.

Use Helm to:
- Find and use popular software packaged as Helm Charts to run in Kubernetes
- Share your own applications as Helm Charts
- Create reproducible builds of your Kubernetes applications
- Intelligently manage your Kubernetes manifest files
- Manage releases of Helm packages.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export GO_LDFLAGS="-X helm.sh/helm/v3/internal/version.version=v%{version} \
                -X helm.sh/helm/v3/internal/version.gitCommit=%{git_commit} \
                -X helm.sh/helm/v3/internal/version.gitTreeState=clean \
                -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMajor=%{k8s_major} \
                -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMinor=%{k8s_minor} \
                -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMajor=%{k8s_major} \
                -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMinor=%{k8s_minor}"
%gobuild -o %{gobuilddir}/bin/helm %{goipath}/cmd/helm

%{gobuilddir}/bin/helm completion bash > helm.bash
%{gobuilddir}/bin/helm completion fish > helm.fish
%{gobuilddir}/bin/helm completion zsh  > helm.zsh

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -Dpm 0644 helm.bash %{buildroot}%{bash_completions_dir}/helm
install -Dpm 0644 helm.fish %{buildroot}%{fish_completions_dir}/helm.fish
install -Dpm 0644 helm.zsh  %{buildroot}%{zsh_completions_dir}/_helm


%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
for test in "TestRenderWithDNS" "TestVCSInstallerNonExistentVersion" "TestVCSInstallerUpdate" \
            "TestVCSInstaller" "TestInsecureTLSRegistryClientTestSuite" "TestInstallRelease_Wait_Interrupted" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc ADOPTERS.md CONTRIBUTING.md README.md SECURITY.md code-of-conduct.md
%{_bindir}/helm
%{bash_completions_dir}/helm
%{fish_completions_dir}/helm.fish
%{zsh_completions_dir}/_helm

%changelog
%autochangelog
